;;;; server.lisp — pure-CL in-memory Redis store + optional TCP RESP peer.
;;;; FULL PORT #184: hermetic peer exceeds Bun (fixtures need no external Redis).

(in-package :clun.redis)

(defstruct (redis-entry (:conc-name re-)
                        (:constructor make-redis-entry))
  (type :string)   ; :string :hash :set :list :zset
  (value nil)
  (expire-ms nil)) ; universal-time ms or NIL

(defstruct (redis-store (:conc-name rs-)
                        (:constructor %make-redis-store))
  (lock (sb-thread:make-mutex :name "clun-redis-store"))
  (db (make-hash-table :test #'equal))
  (channels (make-hash-table :test #'equal))   ; channel → list of queues
  (patterns (make-hash-table :test #'equal))   ; pattern → list of queues
  (subscribers (make-hash-table :test #'eq)))  ; queue → list of channel/pattern specs

(defstruct (sub-queue (:conc-name sq-))
  (lock (sb-thread:make-mutex :name "clun-redis-subq"))
  (messages '())
  (condvar (sb-thread:make-waitqueue :name "clun-redis-subq"))
  (closed nil)
  (client-id nil))

(defun make-redis-store ()
  "Public constructor for a fresh pure-CL Redis store."
  (%make-redis-store))

(defun %now-ms ()
  (floor (* 1000 (get-internal-real-time))
         internal-time-units-per-second))

(defun %expired-p (entry)
  (let ((exp (re-expire-ms entry)))
    (and exp (<= exp (%now-ms)))))

(defun %purge-if-expired (store key)
  (let ((e (gethash key (rs-db store))))
    (when (and e (%expired-p e))
      (remhash key (rs-db store))
      nil)))

(defun %get-entry (store key)
  (%purge-if-expired store key)
  (gethash key (rs-db store)))

(defun %ensure-type (entry type)
  (unless (eq (re-type entry) type)
    (error 'redis-reply-error
           :message "WRONGTYPE Operation against a key holding the wrong kind of value"
           :code "WRONGTYPE")))

(defun %string-value (entry)
  (%ensure-type entry :string)
  (re-value entry))

(defun %set-string (store key value &key nx xx get keepttl ex px exat pxat)
  (let* ((existing (%get-entry store key))
         (old (and existing (eq (re-type existing) :string)
                   (re-value existing))))
    (when (and nx existing)
      (return-from %set-string (if get old nil)))
    (when (and xx (not existing))
      (return-from %set-string (if get old nil)))
    (let ((entry (or existing (make-redis-entry :type :string))))
      (setf (re-type entry) :string
            (re-value entry) value)
      (unless keepttl
        (setf (re-expire-ms entry) nil))
      (cond
        (ex (setf (re-expire-ms entry) (+ (%now-ms) (* ex 1000))))
        (px (setf (re-expire-ms entry) (+ (%now-ms) px)))
        (exat (setf (re-expire-ms entry) (* exat 1000)))
        (pxat (setf (re-expire-ms entry) pxat)))
      (setf (gethash key (rs-db store)) entry)
      (if get old "OK"))))

(defun %glob-match-p (pattern string)
  "Redis-style glob: * ? [abc]. Pure CL."
  (labels ((match (p s)
             (cond
               ((and (null p) (null s)) t)
               ((null p) nil)
               ((char= (car p) #\*)
                (or (match (cdr p) s)
                    (and s (match p (cdr s)))))
               ((null s) nil)
               ((char= (car p) #\?)
                (match (cdr p) (cdr s)))
               ((char= (car p) #\[)
                (let* ((rest (cdr p))
                       (neg (and rest (char= (car rest) #\^)))
                       (body (if neg (cdr rest) rest))
                       (end (position #\] body))
                       (chars (subseq body 0 end))
                       (after (nthcdr (1+ end) body))
                       (ch (car s))
                       (ok (find ch chars)))
                  (when neg (setf ok (not ok)))
                  (and ok (match after (cdr s)))))
               ((char= (car p) (car s))
                (match (cdr p) (cdr s)))
               (t nil))))
    (match (coerce pattern 'list) (coerce string 'list))))

;;; --- pub/sub ----------------------------------------------------------------

(defun %deliver (queue message)
  (sb-thread:with-mutex ((sq-lock queue))
    (unless (sq-closed queue)
      (setf (sq-messages queue) (nconc (sq-messages queue) (list message)))
      (sb-thread:condition-notify (sq-condvar queue)))))

(defun %publish (store channel message)
  (let ((n 0))
    (dolist (q (gethash channel (rs-channels store)))
      (%deliver q (list "message" channel message))
      (incf n))
    (maphash
     (lambda (pattern queues)
       (when (%glob-match-p pattern channel)
         (dolist (q queues)
           (%deliver q (list "pmessage" pattern channel message))
           (incf n))))
     (rs-patterns store))
    n))

(defun %subscribe-channel (store queue channel)
  (pushnew queue (gethash channel (rs-channels store)) :test #'eq)
  (pushnew (cons :channel channel) (gethash queue (rs-subscribers store))
           :test #'equal)
  (length (remove-if-not (lambda (x) (eq (car x) :channel))
                         (gethash queue (rs-subscribers store)))))

(defun %psubscribe (store queue pattern)
  (pushnew queue (gethash pattern (rs-patterns store)) :test #'eq)
  (pushnew (cons :pattern pattern) (gethash queue (rs-subscribers store))
           :test #'equal)
  (length (remove-if-not (lambda (x) (eq (car x) :pattern))
                         (gethash queue (rs-subscribers store)))))

(defun %unsubscribe-channel (store queue channel)
  (let ((list (gethash channel (rs-channels store))))
    (setf (gethash channel (rs-channels store)) (remove queue list :test #'eq)))
  (setf (gethash queue (rs-subscribers store))
        (remove (cons :channel channel) (gethash queue (rs-subscribers store))
                :test #'equal)))

(defun %punsubscribe (store queue pattern)
  (let ((list (gethash pattern (rs-patterns store))))
    (setf (gethash pattern (rs-patterns store)) (remove queue list :test #'eq)))
  (setf (gethash queue (rs-subscribers store))
        (remove (cons :pattern pattern) (gethash queue (rs-subscribers store))
                :test #'equal)))

(defun %unsubscribe-all (store queue)
  (let ((subs (gethash queue (rs-subscribers store))))
    (dolist (s subs)
      (ecase (car s)
        (:channel (%unsubscribe-channel store queue (cdr s)))
        (:pattern (%punsubscribe store queue (cdr s)))))
    (remhash queue (rs-subscribers store))))

;;; --- command executor -------------------------------------------------------

(defun %args-after (args n)
  (nthcdr n args))

(defun %parse-set-options (rest)
  (let ((ex nil) (px nil) (exat nil) (pxat nil)
        (nx nil) (xx nil) (get nil) (keepttl nil))
    (loop for (tok . more) on rest by #'cdr
          do (let ((u (string-upcase tok)))
               (cond
                 ((string= u "EX")
                  (setf ex (parse-integer (car more)))
                  (setf more (cdr more))
                  (setf rest more))
                 ((string= u "PX")
                  (setf px (parse-integer (car more)))
                  (setf more (cdr more)))
                 ((string= u "EXAT")
                  (setf exat (parse-integer (car more)))
                  (setf more (cdr more)))
                 ((string= u "PXAT")
                  (setf pxat (parse-integer (car more)))
                  (setf more (cdr more)))
                 ((string= u "NX") (setf nx t))
                 ((string= u "XX") (setf xx t))
                 ((string= u "GET") (setf get t))
                 ((string= u "KEEPTTL") (setf keepttl t)))))
    (values ex px exat pxat nx xx get keepttl)))

(defun store-execute (store command-args &key sub-queue)
  "Execute one Redis command against STORE. COMMAND-ARGS is a list of strings.
   SUB-QUEUE is the subscriber queue for this connection (Pub/Sub)."
  (sb-thread:with-mutex ((rs-lock store))
    (let* ((cmd (string-upcase (first command-args)))
           (args (rest command-args)))
      (labels ((need (n)
                 (when (< (length args) n)
                   (error 'redis-reply-error
                          :message (format nil "ERR wrong number of arguments for '~A' command"
                                           (string-downcase cmd))
                          :code "ERR")))
               (key (i) (nth i args))
               (as-int (s) (handler-case (parse-integer s)
                             (error ()
                               (error 'redis-reply-error
                                      :message "ERR value is not an integer or out of range"
                                      :code "ERR")))))
        (cond
          ;; Connection
          ((string= cmd "PING")
           (if args (first args) "PONG"))
          ((string= cmd "ECHO")
           (need 1) (first args))
          ((string= cmd "QUIT") "OK")
          ((string= cmd "SELECT")
           (need 1) "OK")
          ((string= cmd "AUTH") "OK")
          ((string= cmd "HELLO")
           (list "server" "clun-redis" "version" "1.0.0" "proto" 2 "mode" "standalone"
                 "role" "master" "modules" '()))
          ((string= cmd "INFO")
           (format nil "# Server~%redis_version:clun-embedded~%redis_mode:standalone~%# Clients~%connected_clients:1~%# Keyspace~%db0:keys=~D~%"
                   (hash-table-count (rs-db store))))
          ((string= cmd "DBSIZE")
           (hash-table-count (rs-db store)))
          ((string= cmd "FLUSHDB")
           (clrhash (rs-db store)) "OK")
          ((string= cmd "FLUSHALL")
           (clrhash (rs-db store)) "OK")
          ((string= cmd "COMMAND")
           '())

          ;; Strings / keys
          ((string= cmd "GET")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (if e (progn (%ensure-type e :string) (re-value e)) nil)))
          ((string= cmd "SET")
           (need 2)
           (multiple-value-bind (ex px exat pxat nx xx get keepttl)
               (%parse-set-options (cddr args))
             (%set-string store (key 0) (key 1)
                          :ex ex :px px :exat exat :pxat pxat
                          :nx nx :xx xx :get get :keepttl keepttl)))
          ((string= cmd "DEL")
           (let ((n 0))
             (dolist (k args)
               (when (gethash k (rs-db store))
                 (remhash k (rs-db store))
                 (incf n)))
             n))
          ((string= cmd "EXISTS")
           (let ((n 0))
             (dolist (k args)
               (when (%get-entry store k) (incf n)))
             n))
          ((string= cmd "INCR")
           (need 1)
           (let* ((k (key 0))
                  (e (%get-entry store k))
                  (v (if e (as-int (%string-value e)) 0))
                  (nv (1+ v)))
             (%set-string store k (princ-to-string nv))
             nv))
          ((string= cmd "INCRBY")
           (need 2)
           (let* ((k (key 0))
                  (e (%get-entry store k))
                  (v (if e (as-int (%string-value e)) 0))
                  (nv (+ v (as-int (key 1)))))
             (%set-string store k (princ-to-string nv))
             nv))
          ((string= cmd "INCRBYFLOAT")
           (need 2)
           (let* ((k (key 0))
                  (e (%get-entry store k))
                  (v (if e (read-from-string (%string-value e)) 0.0d0))
                  (nv (+ (float v 1d0) (read-from-string (key 1))))
                  (s (let ((*read-default-float-format* 'double-float))
                       (format nil "~F" nv))))
             (%set-string store k s)
             s))
          ((string= cmd "DECR")
           (need 1)
           (store-execute store (list "INCRBY" (key 0) "-1")))
          ((string= cmd "DECRBY")
           (need 2)
           (store-execute store (list "INCRBY" (key 0)
                                      (princ-to-string (- (as-int (key 1)))))))
          ((string= cmd "EXPIRE")
           (need 2)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (progn
                   (setf (re-expire-ms e) (+ (%now-ms) (* (as-int (key 1)) 1000)))
                   1)
                 0)))
          ((string= cmd "PEXPIRE")
           (need 2)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (progn
                   (setf (re-expire-ms e) (+ (%now-ms) (as-int (key 1))))
                   1)
                 0)))
          ((string= cmd "EXPIREAT")
           (need 2)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (progn
                   (setf (re-expire-ms e) (* (as-int (key 1)) 1000))
                   1)
                 0)))
          ((string= cmd "TTL")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (cond
               ((null e) -2)
               ((null (re-expire-ms e)) -1)
               (t (max 0 (floor (- (re-expire-ms e) (%now-ms)) 1000))))))
          ((string= cmd "PTTL")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (cond
               ((null e) -2)
               ((null (re-expire-ms e)) -1)
               (t (max 0 (- (re-expire-ms e) (%now-ms)))))))
          ((string= cmd "PERSIST")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (if (and e (re-expire-ms e))
                 (progn (setf (re-expire-ms e) nil) 1)
                 0)))
          ((string= cmd "TYPE")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (string-downcase (symbol-name (re-type e)))
                 "none")))
          ((string= cmd "KEYS")
           (need 1)
           (let ((pat (key 0)) (out '()))
             (maphash (lambda (k v)
                        (declare (ignore v))
                        (when (and (not (%purge-if-expired store k))
                                   (%glob-match-p pat k))
                          (push k out)))
                      (rs-db store))
             (nreverse out)))
          ((string= cmd "SCAN")
           (need 1)
           (let* ((cursor (as-int (key 0)))
                  (match "*")
                  (count 10)
                  (rest (cdr args)))
             (loop for (tok val . more) on rest by #'cddr
                   do (let ((u (string-upcase tok)))
                        (cond
                          ((string= u "MATCH") (setf match val))
                          ((string= u "COUNT") (setf count (as-int val))))))
             (let ((keys '()) (i 0) (collected 0))
               (maphash
                (lambda (k v)
                  (declare (ignore v))
                  (when (and (>= i cursor)
                             (not (%purge-if-expired store k))
                             (%glob-match-p match k)
                             (< collected count))
                    (push k keys)
                    (incf collected))
                  (incf i))
                (rs-db store))
               (list "0" (nreverse keys)))))
          ((string= cmd "MGET")
           (mapcar (lambda (k)
                     (let ((e (%get-entry store k)))
                       (if (and e (eq (re-type e) :string)) (re-value e) nil)))
                   args))
          ((string= cmd "MSET")
           (loop for (k v) on args by #'cddr
                 do (%set-string store k v))
           "OK")
          ((string= cmd "APPEND")
           (need 2)
           (let* ((e (%get-entry store (key 0)))
                  (old (if e (%string-value e) ""))
                  (nv (concatenate 'string old (key 1))))
             (%set-string store (key 0) nv)
             (length nv)))
          ((string= cmd "STRLEN")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (if e (length (%string-value e)) 0)))
          ((string= cmd "GETSET")
           (need 2)
           (let* ((e (%get-entry store (key 0)))
                  (old (if e (%string-value e) nil)))
             (%set-string store (key 0) (key 1))
             old))
          ((string= cmd "SETNX")
           (need 2)
           (if (%get-entry store (key 0))
               0
               (progn (%set-string store (key 0) (key 1)) 1)))
          ((string= cmd "RENAME")
           (need 2)
           (let ((e (%get-entry store (key 0))))
             (unless e
               (error 'redis-reply-error :message "ERR no such key" :code "ERR"))
             (setf (gethash (key 1) (rs-db store)) e)
             (remhash (key 0) (rs-db store))
             "OK"))
          ((string= cmd "RENAMENX")
           (need 2)
           (if (%get-entry store (key 1))
               0
               (progn (store-execute store (list "RENAME" (key 0) (key 1))) 1)))

          ;; Hash
          ((string= cmd "HSET")
           (need 3)
           (let* ((k (key 0))
                  (e (or (%get-entry store k)
                         (let ((ne (make-redis-entry
                                    :type :hash
                                    :value (make-hash-table :test #'equal))))
                           (setf (gethash k (rs-db store)) ne)
                           ne)))
                  (ht (progn (%ensure-type e :hash) (re-value e)))
                  (added 0))
             (loop for (f v) on (cdr args) by #'cddr
                   do (unless (gethash f ht) (incf added))
                      (setf (gethash f ht) v))
             added))
          ((string= cmd "HGET")
           (need 2)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (progn (%ensure-type e :hash)
                        (gethash (key 1) (re-value e)))
                 nil)))
          ((string= cmd "HMSET")
           (store-execute store (cons "HSET" args))
           "OK")
          ((string= cmd "HMGET")
           (need 2)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (progn
                   (%ensure-type e :hash)
                   (mapcar (lambda (f) (gethash f (re-value e))) (cdr args)))
                 (mapcar (constantly nil) (cdr args)))))
          ((string= cmd "HDEL")
           (need 2)
           (let ((e (%get-entry store (key 0))) (n 0))
             (when e
               (%ensure-type e :hash)
               (dolist (f (cdr args))
                 (when (remhash f (re-value e)) (incf n))))
             n))
          ((string= cmd "HEXISTS")
           (need 2)
           (let ((e (%get-entry store (key 0))))
             (if (and e (gethash (key 1) (progn (%ensure-type e :hash)
                                                (re-value e))))
                 1 0)))
          ((string= cmd "HGETALL")
           (need 1)
           (let ((e (%get-entry store (key 0))) (out '()))
             (when e
               (%ensure-type e :hash)
               (maphash (lambda (f v) (push f out) (push v out)) (re-value e)))
             (nreverse out)))
          ((string= cmd "HKEYS")
           (need 1)
           (let ((e (%get-entry store (key 0))) (out '()))
             (when e
               (%ensure-type e :hash)
               (maphash (lambda (f v) (declare (ignore v)) (push f out))
                        (re-value e)))
             (nreverse out)))
          ((string= cmd "HVALS")
           (need 1)
           (let ((e (%get-entry store (key 0))) (out '()))
             (when e
               (%ensure-type e :hash)
               (maphash (lambda (f v) (declare (ignore f)) (push v out))
                        (re-value e)))
             (nreverse out)))
          ((string= cmd "HLEN")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (progn (%ensure-type e :hash)
                        (hash-table-count (re-value e)))
                 0)))
          ((string= cmd "HINCRBY")
           (need 3)
           (let* ((e (or (%get-entry store (key 0))
                         (let ((ne (make-redis-entry
                                    :type :hash
                                    :value (make-hash-table :test #'equal))))
                           (setf (gethash (key 0) (rs-db store)) ne) ne)))
                  (ht (progn (%ensure-type e :hash) (re-value e)))
                  (cur (let ((v (gethash (key 1) ht)))
                         (if v (as-int v) 0)))
                  (nv (+ cur (as-int (key 2)))))
             (setf (gethash (key 1) ht) (princ-to-string nv))
             nv))
          ((string= cmd "HINCRBYFLOAT")
           (need 3)
           (let* ((e (or (%get-entry store (key 0))
                         (let ((ne (make-redis-entry
                                    :type :hash
                                    :value (make-hash-table :test #'equal))))
                           (setf (gethash (key 0) (rs-db store)) ne) ne)))
                  (ht (progn (%ensure-type e :hash) (re-value e)))
                  (cur (let ((v (gethash (key 1) ht)))
                         (if v (read-from-string v) 0.0d0)))
                  (nv (+ (float cur 1d0) (read-from-string (key 2))))
                  (s (format nil "~F" nv)))
             (setf (gethash (key 1) ht) s)
             s))
          ((string= cmd "HSETNX")
           (need 3)
           (let* ((e (or (%get-entry store (key 0))
                         (let ((ne (make-redis-entry
                                    :type :hash
                                    :value (make-hash-table :test #'equal))))
                           (setf (gethash (key 0) (rs-db store)) ne) ne)))
                  (ht (progn (%ensure-type e :hash) (re-value e))))
             (if (gethash (key 1) ht)
                 0
                 (progn (setf (gethash (key 1) ht) (key 2)) 1))))
          ((string= cmd "HSTRLEN")
           (need 2)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (let ((v (gethash (key 1) (progn (%ensure-type e :hash)
                                                  (re-value e)))))
                   (if v (length v) 0))
                 0)))
          ((string= cmd "HSCAN")
           (need 2)
           (let ((all (store-execute store (list "HGETALL" (key 0)))))
             (list "0" all)))

          ;; Sets
          ((string= cmd "SADD")
           (need 2)
           (let* ((e (or (%get-entry store (key 0))
                         (let ((ne (make-redis-entry
                                    :type :set
                                    :value (make-hash-table :test #'equal))))
                           (setf (gethash (key 0) (rs-db store)) ne) ne)))
                  (ht (progn (%ensure-type e :set) (re-value e)))
                  (n 0))
             (dolist (m (cdr args))
               (unless (gethash m ht)
                 (setf (gethash m ht) t)
                 (incf n)))
             n))
          ((string= cmd "SREM")
           (need 2)
           (let ((e (%get-entry store (key 0))) (n 0))
             (when e
               (%ensure-type e :set)
               (dolist (m (cdr args))
                 (when (remhash m (re-value e)) (incf n))))
             n))
          ((string= cmd "SISMEMBER")
           (need 2)
           (let ((e (%get-entry store (key 0))))
             (if (and e (gethash (key 1) (progn (%ensure-type e :set)
                                                (re-value e))))
                 1 0)))
          ((string= cmd "SMEMBERS")
           (need 1)
           (let ((e (%get-entry store (key 0))) (out '()))
             (when e
               (%ensure-type e :set)
               (maphash (lambda (m v) (declare (ignore v)) (push m out))
                        (re-value e)))
             (nreverse out)))
          ((string= cmd "SCARD")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (progn (%ensure-type e :set)
                        (hash-table-count (re-value e)))
                 0)))
          ((string= cmd "SPOP")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (when e
               (%ensure-type e :set)
               (let ((ht (re-value e)))
                 (when (plusp (hash-table-count ht))
                   (maphash (lambda (m v)
                              (declare (ignore v))
                              (remhash m ht)
                              (return-from store-execute m))
                            ht))))
             nil))
          ((string= cmd "SRANDMEMBER")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (when e
               (%ensure-type e :set)
               (maphash (lambda (m v)
                          (declare (ignore v))
                          (return-from store-execute m))
                        (re-value e)))
             nil))
          ((string= cmd "SMOVE")
           (need 3)
           (let ((src (%get-entry store (key 0))))
             (if (and src
                      (gethash (key 2)
                               (progn (%ensure-type src :set) (re-value src))))
                 (progn
                   (store-execute store (list "SREM" (key 0) (key 2)))
                   (store-execute store (list "SADD" (key 1) (key 2)))
                   1)
                 0)))
          ((string= cmd "SUNION")
           (let ((out (make-hash-table :test #'equal)))
             (dolist (k args)
               (let ((e (%get-entry store k)))
                 (when e
                   (%ensure-type e :set)
                   (maphash (lambda (m v) (declare (ignore v))
                              (setf (gethash m out) t))
                            (re-value e)))))
             (let ((r '()))
               (maphash (lambda (m v) (declare (ignore v)) (push m r)) out)
               r)))
          ((string= cmd "SINTER")
           (if (null args)
               '()
               (let ((first (store-execute store (list "SMEMBERS" (first args)))))
                 (remove-if-not
                  (lambda (m)
                    (every (lambda (k)
                             (eql 1 (store-execute store
                                                   (list "SISMEMBER" k m))))
                           (rest args)))
                  first))))
          ((string= cmd "SDIFF")
           (if (null args)
               '()
               (let ((first (store-execute store (list "SMEMBERS" (first args)))))
                 (remove-if
                  (lambda (m)
                    (some (lambda (k)
                            (eql 1 (store-execute store
                                                  (list "SISMEMBER" k m))))
                          (rest args)))
                  first))))
          ((string= cmd "SSCAN")
           (need 2)
           (list "0" (store-execute store (list "SMEMBERS" (key 0)))))

          ;; Lists
          ((string= cmd "LPUSH")
           (need 2)
           (let* ((e (or (%get-entry store (key 0))
                         (let ((ne (make-redis-entry :type :list :value '())))
                           (setf (gethash (key 0) (rs-db store)) ne) ne)))
                  (lst (progn (%ensure-type e :list) (re-value e))))
             (dolist (v (cdr args))
               (push v lst))
             (setf (re-value e) lst)
             (length lst)))
          ((string= cmd "RPUSH")
           (need 2)
           (let* ((e (or (%get-entry store (key 0))
                         (let ((ne (make-redis-entry :type :list :value '())))
                           (setf (gethash (key 0) (rs-db store)) ne) ne)))
                  (lst (progn (%ensure-type e :list) (re-value e))))
             (setf (re-value e) (append lst (cdr args)))
             (length (re-value e))))
          ((string= cmd "LPOP")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (when e
               (%ensure-type e :list)
               (let ((lst (re-value e)))
                 (when lst
                   (let ((v (car lst)))
                     (setf (re-value e) (cdr lst))
                     (return-from store-execute v)))))
             nil))
          ((string= cmd "RPOP")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (when e
               (%ensure-type e :list)
               (let ((lst (re-value e)))
                 (when lst
                   (let* ((rev (reverse lst))
                          (v (car rev)))
                     (setf (re-value e) (nreverse (cdr rev)))
                     (return-from store-execute v)))))
             nil))
          ((string= cmd "LLEN")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (if e (progn (%ensure-type e :list) (length (re-value e))) 0)))
          ((string= cmd "LRANGE")
           (need 3)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (let* ((lst (progn (%ensure-type e :list) (re-value e)))
                        (len (length lst))
                        (start (as-int (key 1)))
                        (stop (as-int (key 2))))
                   (when (minusp start) (setf start (+ len start)))
                   (when (minusp stop) (setf stop (+ len stop)))
                   (setf start (max 0 start)
                         stop (min (1- len) stop))
                   (if (> start stop)
                       '()
                       (subseq lst start (1+ stop))))
                 '())))
          ((string= cmd "LINDEX")
           (need 2)
           (let ((e (%get-entry store (key 0))))
             (when e
               (%ensure-type e :list)
               (let* ((lst (re-value e))
                      (len (length lst))
                      (i (as-int (key 1))))
                 (when (minusp i) (setf i (+ len i)))
                 (when (and (>= i 0) (< i len))
                   (return-from store-execute (nth i lst)))))
             nil))
          ((string= cmd "LSET")
           (need 3)
           (let ((e (%get-entry store (key 0))))
             (unless e
               (error 'redis-reply-error :message "ERR no such key" :code "ERR"))
             (%ensure-type e :list)
             (let* ((lst (copy-list (re-value e)))
                    (len (length lst))
                    (i (as-int (key 1))))
               (when (minusp i) (setf i (+ len i)))
               (unless (and (>= i 0) (< i len))
                 (error 'redis-reply-error
                        :message "ERR index out of range" :code "ERR"))
               (setf (nth i lst) (key 2)
                     (re-value e) lst)
               "OK")))
          ((string= cmd "LREM")
           (need 3)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (let* ((count (as-int (key 1)))
                        (val (key 2))
                        (lst (progn (%ensure-type e :list) (re-value e)))
                        (removed 0)
                        (out '()))
                   (if (zerop count)
                       (dolist (x lst)
                         (if (string= x val)
                             (incf removed)
                             (push x out)))
                       (let ((left (abs count)))
                         (if (plusp count)
                             (dolist (x lst)
                               (if (and (plusp left) (string= x val))
                                   (progn (decf left) (incf removed))
                                   (push x out)))
                             (let ((rev (reverse lst)))
                               (dolist (x rev)
                                 (if (and (plusp left) (string= x val))
                                     (progn (decf left) (incf removed))
                                     (push x out)))
                               (setf out (nreverse out))))))
                   (setf (re-value e) (nreverse out))
                   removed)
                 0)))
          ((string= cmd "LTRIM")
           (need 3)
           (let ((range (store-execute store
                                       (list "LRANGE" (key 0) (key 1) (key 2))))
                 (e (%get-entry store (key 0))))
             (when e
               (%ensure-type e :list)
               (setf (re-value e) range))
             "OK"))
          ((string= cmd "RPOPLPUSH")
           (need 2)
           (let ((v (store-execute store (list "RPOP" (key 0)))))
             (when v
               (store-execute store (list "LPUSH" (key 1) v)))
             v))
          ((string= cmd "LMOVE")
           (need 4)
           (let* ((from (string-upcase (key 2)))
                  (to (string-upcase (key 3)))
                  (v (store-execute store
                                    (list (if (string= from "LEFT") "LPOP" "RPOP")
                                          (key 0)))))
             (when v
               (store-execute store
                              (list (if (string= to "LEFT") "LPUSH" "RPUSH")
                                    (key 1) v)))
             v))

          ;; Sorted sets (score→member map via alist sorted by score)
          ((string= cmd "ZADD")
           (need 3)
           (let* ((e (or (%get-entry store (key 0))
                         (let ((ne (make-redis-entry :type :zset :value '())))
                           (setf (gethash (key 0) (rs-db store)) ne) ne)))
                  (pairs (progn (%ensure-type e :zset) (re-value e)))
                  (added 0)
                  (rest args))
             ;; skip options NX/XX/GT/LT/CH/INCR for core path; handle score member pairs
             (loop while rest
                   for score = (read-from-string (pop rest))
                   for member = (pop rest)
                   do (let ((existing (assoc member pairs :test #'string=)))
                        (if existing
                            (setf (cdr existing) score)
                            (progn
                              (push (cons member score) pairs)
                              (incf added)))))
             (setf (re-value e)
                   (sort pairs #'< :key #'cdr))
             added))
          ((string= cmd "ZREM")
           (need 2)
           (let ((e (%get-entry store (key 0))) (n 0))
             (when e
               (%ensure-type e :zset)
               (let ((pairs (re-value e)))
                 (dolist (m (cdr args))
                   (when (assoc m pairs :test #'string=)
                     (setf pairs (remove m pairs :key #'car :test #'string=))
                     (incf n)))
                 (setf (re-value e) pairs)))
             n))
          ((string= cmd "ZSCORE")
           (need 2)
           (let ((e (%get-entry store (key 0))))
             (when e
               (%ensure-type e :zset)
               (let ((p (assoc (key 1) (re-value e) :test #'string=)))
                 (when p
                   (return-from store-execute (format nil "~F" (cdr p))))))
             nil))
          ((string= cmd "ZCARD")
           (need 1)
           (let ((e (%get-entry store (key 0))))
             (if e (progn (%ensure-type e :zset) (length (re-value e))) 0)))
          ((string= cmd "ZRANGE")
           (need 3)
           (let ((e (%get-entry store (key 0)))
                 (withscores (member "WITHSCORES" args :test #'string-equal)))
             (if e
                 (let* ((pairs (progn (%ensure-type e :zset) (re-value e)))
                        (len (length pairs))
                        (start (as-int (key 1)))
                        (stop (as-int (key 2))))
                   (when (minusp start) (setf start (+ len start)))
                   (when (minusp stop) (setf stop (+ len stop)))
                   (setf start (max 0 start) stop (min (1- len) stop))
                   (if (> start stop)
                       '()
                       (let ((slice (subseq pairs start (1+ stop))))
                         (if withscores
                             (mapcan (lambda (p)
                                       (list (car p) (format nil "~F" (cdr p))))
                                     slice)
                             (mapcar #'car slice)))))
                 '())))
          ((string= cmd "ZREVRANGE")
           (need 3)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (let* ((pairs (reverse (progn (%ensure-type e :zset)
                                               (copy-list (re-value e)))))
                        (start (as-int (key 1)))
                        (stop (as-int (key 2)))
                        (withscores (member "WITHSCORES" (cdddr args)
                                            :test #'string-equal))
                        (len (length pairs)))
                   (when (minusp start) (setf start (+ len start)))
                   (when (minusp stop) (setf stop (+ len stop)))
                   (setf start (max 0 start)
                         stop (min (1- len) stop))
                   (if (or (null pairs) (> start stop) (minusp stop))
                       '()
                       (let ((slice (subseq pairs start (1+ stop))))
                         (if withscores
                             (mapcan (lambda (p)
                                       (list (car p) (format nil "~F" (cdr p))))
                                     slice)
                             (mapcar #'car slice)))))
                 '())))
          ((string= cmd "ZRANK")
           (need 2)
           (let ((e (%get-entry store (key 0))))
             (when e
               (%ensure-type e :zset)
               (let ((i 0))
                 (dolist (p (re-value e))
                   (when (string= (car p) (key 1))
                     (return-from store-execute i))
                   (incf i))))
             nil))
          ((string= cmd "ZINCRBY")
           (need 3)
           (let* ((e (or (%get-entry store (key 0))
                         (let ((ne (make-redis-entry :type :zset :value '())))
                           (setf (gethash (key 0) (rs-db store)) ne) ne)))
                  (pairs (progn (%ensure-type e :zset) (re-value e)))
                  (inc (read-from-string (key 1)))
                  (member (key 2))
                  (existing (assoc member pairs :test #'string=))
                  (ns (if existing (+ (cdr existing) inc) inc)))
             (if existing
                 (setf (cdr existing) ns)
                 (push (cons member ns) pairs))
             (setf (re-value e) (sort pairs #'< :key #'cdr))
             (format nil "~F" ns)))
          ((string= cmd "ZRANGEBYSCORE")
           (need 3)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (let* ((pairs (progn (%ensure-type e :zset) (re-value e)))
                        (min (if (string= (key 1) "-inf")
                                 most-negative-double-float
                                 (read-from-string (key 1))))
                        (max (if (string= (key 2) "+inf")
                                 most-positive-double-float
                                 (read-from-string (key 2)))))
                   (mapcar #'car
                           (remove-if-not
                            (lambda (p) (and (<= min (cdr p)) (<= (cdr p) max)))
                            pairs)))
                 '())))
          ((string= cmd "ZREMRANGEBYSCORE")
           (need 3)
           (let ((e (%get-entry store (key 0))))
             (if e
                 (let* ((pairs (progn (%ensure-type e :zset) (re-value e)))
                        (min (if (string= (key 1) "-inf")
                                 most-negative-double-float
                                 (read-from-string (key 1))))
                        (max (if (string= (key 2) "+inf")
                                 most-positive-double-float
                                 (read-from-string (key 2))))
                        (kept '())
                        (n 0))
                   (dolist (p pairs)
                     (if (and (<= min (cdr p)) (<= (cdr p) max))
                         (incf n)
                         (push p kept)))
                   (setf (re-value e) (nreverse kept))
                   n)
                 0)))

          ;; Pub/Sub
          ((string= cmd "PUBLISH")
           (need 2)
           (%publish store (key 0) (key 1)))
          ((string= cmd "SUBSCRIBE")
           (unless sub-queue
             (error 'redis-reply-error
                    :message "ERR SUBSCRIBE requires a connection queue"
                    :code "ERR"))
           (mapcar (lambda (ch)
                     (let ((n (%subscribe-channel store sub-queue ch)))
                       (list "subscribe" ch n)))
                   args))
          ((string= cmd "PSUBSCRIBE")
           (unless sub-queue
             (error 'redis-reply-error
                    :message "ERR PSUBSCRIBE requires a connection queue"
                    :code "ERR"))
           (mapcar (lambda (pat)
                     (let ((n (%psubscribe store sub-queue pat)))
                       (list "psubscribe" pat n)))
                   args))
          ((string= cmd "UNSUBSCRIBE")
           (unless sub-queue
             (error 'redis-reply-error
                    :message "ERR UNSUBSCRIBE requires a connection queue"
                    :code "ERR"))
           (if args
               (mapcar (lambda (ch)
                         (%unsubscribe-channel store sub-queue ch)
                         (list "unsubscribe" ch
                               (length (gethash sub-queue (rs-subscribers store)))))
                       args)
               (progn
                 (%unsubscribe-all store sub-queue)
                 (list (list "unsubscribe" nil 0)))))
          ((string= cmd "PUNSUBSCRIBE")
           (unless sub-queue
             (error 'redis-reply-error
                    :message "ERR PUNSUBSCRIBE requires a connection queue"
                    :code "ERR"))
           (if args
               (mapcar (lambda (pat)
                         (%punsubscribe store sub-queue pat)
                         (list "punsubscribe" pat
                               (length (gethash sub-queue (rs-subscribers store)))))
                       args)
               (progn
                 (let ((subs (copy-list (gethash sub-queue (rs-subscribers store)))))
                   (dolist (s subs)
                     (when (eq (car s) :pattern)
                       (%punsubscribe store sub-queue (cdr s)))))
                 (list (list "punsubscribe" nil 0)))))

          ;; Transactions (minimal MULTI/EXEC buffering on store side is client-side)
          ((string= cmd "MULTI") "OK")
          ((string= cmd "EXEC") '())
          ((string= cmd "DISCARD") "OK")
          ((string= cmd "WATCH") "OK")
          ((string= cmd "UNWATCH") "OK")

          (t
           (error 'redis-reply-error
                  :message (format nil "ERR unknown command '~A'"
                                   (string-downcase cmd))
                  :code "ERR")))))))

;;; --- TCP embedded peer ------------------------------------------------------

(defstruct (embedded-server (:conc-name es-))
  host
  port
  store
  socket
  thread
  (running nil)
  (lock (sb-thread:make-mutex :name "clun-redis-es")))

(defparameter *embedded-servers* nil)

(defun %handle-client (store client-socket)
  (let ((stream (sb-bsd-sockets:socket-make-stream
                 client-socket
                 :element-type '(unsigned-byte 8)
                 :input t :output t :buffering :full))
        (queue (make-sub-queue)))
    (unwind-protect
         (handler-case
             (loop
               (let ((args (resp-decode-from-stream stream :errors-as-condition nil)))
                 (when (and (consp args) (eq (car args) :error))
                   (write-sequence (resp-encode-error (second args)) stream)
                   (force-output stream)
                   (return))
                 (unless (listp args)
                   (write-sequence (resp-encode-error "ERR protocol error") stream)
                   (force-output stream)
                   (return))
                 (let* ((cmd (string-upcase (first args)))
                        (pubsub-cmd (member cmd '("SUBSCRIBE" "PSUBSCRIBE"
                                                  "UNSUBSCRIBE" "PUNSUBSCRIBE")
                                            :test #'string=)))
                   (handler-case
                       (let ((result (store-execute store args
                                                    :sub-queue queue)))
                         (cond
                           (pubsub-cmd
                            (dolist (msg (if (and (consp result)
                                                  (consp (car result)))
                                             result
                                             (list result)))
                              (write-sequence (resp-encode-value msg) stream))
                            (force-output stream)
                            ;; Enter pubsub read loop: also drain messages
                            (loop
                              (let ((msg
                                      (sb-thread:with-mutex ((sq-lock queue))
                                        (loop while (and (null (sq-messages queue))
                                                         (not (sq-closed queue)))
                                              do (sb-thread:condition-wait
                                                  (sq-condvar queue)
                                                  (sq-lock queue)
                                                  :timeout 0.05))
                                        (when (sq-messages queue)
                                          (let ((m (pop (sq-messages queue))))
                                            m)))))
                                (when msg
                                  (write-sequence (resp-encode-value msg) stream)
                                  (force-output stream))
                                ;; Non-blocking check for client commands
                                (when (listen stream)
                                  (return)))))
                           (t
                            (write-sequence (resp-encode-value result) stream)
                            (force-output stream)
                            (when (string= cmd "QUIT")
                              (return)))))
                     (redis-reply-error (e)
                       (write-sequence
                        (resp-encode-error (redis-error-message e)) stream)
                       (force-output stream))
                     (error (e)
                       (write-sequence
                        (resp-encode-error (format nil "ERR ~A" e)) stream)
                       (force-output stream))))))
           (end-of-file ())
           (error ()))
      (%unsubscribe-all store queue)
      (ignore-errors (close stream))
      (ignore-errors (sb-bsd-sockets:socket-close client-socket)))))

(defun start-embedded-redis (&key (host "127.0.0.1") (port 0) store)
  "Start a pure-CL TCP RESP peer. PORT 0 picks an ephemeral port.
   Returns the EMBEDDED-SERVER. Exceeds Bun: hermetic peer in-process."
  (let* ((store (or store (make-redis-store)))
         (socket (make-instance 'sb-bsd-sockets:inet-socket
                                :type :stream :protocol :tcp))
         (addr (sb-bsd-sockets:make-inet-address host)))
    (setf (sb-bsd-sockets:sockopt-reuse-address socket) t)
    (sb-bsd-sockets:socket-bind socket addr port)
    (sb-bsd-sockets:socket-listen socket 32)
    (multiple-value-bind (_h real-port)
        (sb-bsd-sockets:socket-name socket)
      (declare (ignore _h))
      (let* ((server (make-embedded-server
                      :host host :port real-port :store store
                      :socket socket :running t))
             (thread
               (sb-thread:make-thread
                (lambda ()
                  (loop while (es-running server)
                        do (handler-case
                               (let ((client
                                       (sb-bsd-sockets:socket-accept socket)))
                                 (sb-thread:make-thread
                                  (lambda () (%handle-client store client))
                                  :name "clun-redis-client"))
                             (error ()
                               (sleep 0.01)))))
                :name "clun-redis-accept")))
        (setf (es-thread server) thread)
        (push server *embedded-servers*)
        server))))

(defun stop-embedded-redis (server)
  (when server
    (setf (es-running server) nil)
    (ignore-errors (sb-bsd-sockets:socket-close (es-socket server)))
    (when (and (es-thread server)
               (sb-thread:thread-alive-p (es-thread server)))
      (ignore-errors (sb-thread:terminate-thread (es-thread server))))
    (setf *embedded-servers* (remove server *embedded-servers*))
    t))

(defun embedded-redis-port (server) (es-port server))
(defun embedded-redis-host (server) (es-host server))

(defmacro with-embedded-redis ((server-var &rest keys) &body body)
  `(let ((,server-var (start-embedded-redis ,@keys)))
     (unwind-protect (progn ,@body)
       (stop-embedded-redis ,server-var))))
