;;;; assert.lisp — node:assert. build-node-assert RETURNS the assert(value,message?)
;;;; function; the other checks hang off it as properties. AssertionError is a real
;;;; Error object (name/code patched) raised via throw-js-value.

(in-package :clun.runtime)

(defun %assert-fail (message)
  "Construct an AssertionError (global Error with name/code patched) and throw it."
  (let* ((err-ctor (eng:js-get (eng:realm-global eng:*realm*) "Error"))
         (msg (if (undef-p message) "Failed" (->str message)))
         (err (eng:js-construct err-ctor (list msg))))
    (eng:js-set err "name" "AssertionError" nil)
    (eng:js-set err "code" "ERR_ASSERTION" nil)
    (eng:throw-js-value err)))

(defun %assert-ok (value message)
  (unless (eng:js-truthy value)
    (%assert-fail (if (undef-p message) "The expression evaluated to a falsy value" message))))

(defun %assert-check (ok message default)
  (unless ok (%assert-fail (if (undef-p message) default message))))

(defun %assert-throws-p (fn)
  "Call FN; return :no-throw if it did not throw, else (list thrown-value)."
  (handler-case (progn (eng:js-call fn (undef) '()) :no-throw)
    (eng:js-condition (c) (list (eng:js-condition-value c)))))

(defun %assert-expected-ok (thrown expected)
  "Best-effort validation of a thrown value against EXPECTED (a matcher)."
  (cond
    ((undef-p expected) t)
    ((eng:callable-p expected)
     ;; An error constructor/class: the thrown value must be an instance of it.
     (eng:js-instanceof thrown expected))
    ((eng:js-object-p expected)
     (let ((test (eng:js-get expected "test")))
       (if (eng:callable-p test)
           (eng:js-truthy (eng:js-call test expected (list (->str thrown))))
           t)))
    (t t)))

(defun build-node-assert ()
  (let ((o (eng:make-native-function
            "assert" 2
            (lambda (this args) (declare (ignore this))
              (%assert-ok (a args 0) (a args 1)) (undef)))))
    (labels ((m (name arity fn) (eng:install-method o name arity fn)))
      (m "ok" 2 (lambda (this args) (declare (ignore this))
                  (%assert-ok (a args 0) (a args 1)) (undef)))
      ;; equal/notEqual are LOOSE (==) per Node; strict* use ===.
      (m "equal" 3 (lambda (this args) (declare (ignore this))
                     (%assert-check (eng:js-loose-eq (a args 0) (a args 1)) (a args 2)
                                    "Values are not equal") (undef)))
      (m "notEqual" 3 (lambda (this args) (declare (ignore this))
                        (%assert-check (not (eng:js-loose-eq (a args 0) (a args 1))) (a args 2)
                                       "Values should not be equal") (undef)))
      (m "strictEqual" 3 (lambda (this args) (declare (ignore this))
                           (%assert-check (eng:js-strict-eq (a args 0) (a args 1)) (a args 2)
                                          "Values are not strictly equal") (undef)))
      (m "notStrictEqual" 3 (lambda (this args) (declare (ignore this))
                              (%assert-check (not (eng:js-strict-eq (a args 0) (a args 1))) (a args 2)
                                             "Values should not be strictly equal") (undef)))
      (m "deepEqual" 3 (lambda (this args) (declare (ignore this))
                         (%assert-check (eng:js-deep-equal (a args 0) (a args 1)) (a args 2)
                                        "Values are not deeply equal") (undef)))
      (m "deepStrictEqual" 3 (lambda (this args) (declare (ignore this))
                               (%assert-check (eng:js-deep-equal (a args 0) (a args 1)) (a args 2)
                                              "Values are not deeply equal") (undef)))
      (m "notDeepEqual" 3 (lambda (this args) (declare (ignore this))
                            (%assert-check (not (eng:js-deep-equal (a args 0) (a args 1))) (a args 2)
                                           "Values should not be deeply equal") (undef)))
      (m "notDeepStrictEqual" 3 (lambda (this args) (declare (ignore this))
                                  (%assert-check (not (eng:js-deep-equal (a args 0) (a args 1))) (a args 2)
                                                 "Values should not be deeply equal") (undef)))
      (m "throws" 3 (lambda (this args) (declare (ignore this))
                      (let ((r (%assert-throws-p (a args 0))))
                        (if (eq r :no-throw)
                            (%assert-fail (let ((mg (a args 2)))
                                            (if (undef-p mg) "Missing expected exception" mg)))
                            (unless (%assert-expected-ok (car r) (a args 1))
                              (%assert-fail (a args 2)))))
                      (undef)))
      (m "doesNotThrow" 3 (lambda (this args) (declare (ignore this))
                            (let ((r (%assert-throws-p (a args 0))))
                              (unless (eq r :no-throw)
                                (%assert-fail (let ((mg (a args 2)))
                                                (if (undef-p mg) "Got unwanted exception" mg)))))
                            (undef)))
      (m "match" 3 (lambda (this args) (declare (ignore this))
                     (let* ((str (->str (a args 0))) (re (a args 1))
                            (test (eng:js-get re "test")))
                       (%assert-check (and (eng:callable-p test)
                                           (eng:js-truthy (eng:js-call test re (list str))))
                                      (a args 2) "The input did not match the regular expression"))
                     (undef)))
      (m "doesNotMatch" 3 (lambda (this args) (declare (ignore this))
                            (let* ((str (->str (a args 0))) (re (a args 1))
                                   (test (eng:js-get re "test")))
                              (%assert-check
                               (not (and (eng:callable-p test)
                                         (eng:js-truthy (eng:js-call test re (list str)))))
                               (a args 2) "The input was expected to not match the regular expression"))
                            (undef)))
      (m "fail" 1 (lambda (this args) (declare (ignore this))
                    (%assert-fail (a args 0)) (undef)))
      (eng:data-prop o "ok" (eng:js-get o "ok"))
      (eng:data-prop o "strict" o)
      ;; assert.AssertionError: a constructor producing name/code-correct errors. (Full
      ;; `e instanceof assert.AssertionError` needs a dedicated prototype — a documented 🟡.)
      (eng:data-prop o "AssertionError"
        (eng:make-native-function "AssertionError" 1
          (lambda (this args) (declare (ignore this)) (%assert-make-error (a args 0)))
          :construct (lambda (args nt) (declare (ignore nt)) (%assert-make-error (a args 0))))))
    o))

(defun %assert-make-error (options)
  "An AssertionError object (name/code patched) from an options object or a message."
  (let* ((err-ctor (eng:js-get (eng:realm-global eng:*realm*) "Error"))
         (msg (cond ((eng:js-string-p options) options)
                    ((and (eng:js-object-p options)
                          (eng:js-string-p (eng:js-get options "message")))
                     (eng:js-get options "message"))
                    (t "Failed")))
         (err (eng:js-construct err-ctor (list msg))))
    (eng:js-set err "name" "AssertionError" nil)
    (eng:js-set err "code" "ERR_ASSERTION" nil)
    err))

(register-node-builtin "assert" #'build-node-assert)
