;;;; os.lisp — node:os. Host info via clun.sys; values coerced to JS types.
;;;; loadavg/cpu-times are stubbed to zeros (no portable ANSI source).

(in-package :clun.runtime)

(defun %os-cpu ()
  (let ((cpu (eng:new-object)) (times (eng:new-object)))
    (eng:data-prop times "user" 0.0d0)
    (eng:data-prop times "nice" 0.0d0)
    (eng:data-prop times "sys" 0.0d0)
    (eng:data-prop times "idle" 0.0d0)
    (eng:data-prop times "irq" 0.0d0)
    (eng:data-prop cpu "model" "unknown")
    (eng:data-prop cpu "speed" 0.0d0)
    (eng:data-prop cpu "times" times)
    cpu))

(defun %os-user-info ()
  (let ((o (eng:new-object)))
    (eng:data-prop o "username" (or (clun.sys:getenv "USER") (clun.sys:getenv "LOGNAME") "user"))
    (eng:data-prop o "uid" -1.0d0)
    (eng:data-prop o "gid" -1.0d0)
    (eng:data-prop o "shell" (or (clun.sys:getenv "SHELL") eng:+null+))
    (eng:data-prop o "homedir" (clun.sys:homedir))
    o))

(defun build-node-os ()
  (let ((o (eng:new-object)))
    (labels ((m (name arity fn) (eng:install-method o name arity fn)))
      (eng:data-prop o "EOL" (string #\Newline))
      (m "platform" 0 (lambda (this args) (declare (ignore this args)) (clun.sys:platform-name)))
      (m "arch" 0 (lambda (this args) (declare (ignore this args)) (clun.sys:machine-arch)))
      (m "type" 0 (lambda (this args) (declare (ignore this args)) (clun.sys:os-type)))
      (m "release" 0 (lambda (this args) (declare (ignore this args)) (clun.sys:os-release)))
      (m "hostname" 0 (lambda (this args) (declare (ignore this args)) (clun.sys:hostname)))
      (m "tmpdir" 0 (lambda (this args) (declare (ignore this args)) (clun.sys:tmpdir)))
      (m "homedir" 0 (lambda (this args) (declare (ignore this args)) (clun.sys:homedir)))
      (m "endianness" 0 (lambda (this args) (declare (ignore this args)) "LE"))
      (m "uptime" 0 (lambda (this args) (declare (ignore this args))
                      (coerce (clun.sys:uptime-seconds) 'double-float)))
      (m "totalmem" 0 (lambda (this args) (declare (ignore this args))
                        (coerce (clun.sys:total-memory) 'double-float)))
      (m "freemem" 0 (lambda (this args) (declare (ignore this args))
                       (coerce (clun.sys:free-memory) 'double-float)))
      (m "loadavg" 0 (lambda (this args) (declare (ignore this args))
                       (eng:new-array (list 0.0d0 0.0d0 0.0d0))))
      (m "cpus" 0 (lambda (this args) (declare (ignore this args))
                    (eng:new-array (loop repeat (clun.sys:cpu-count) collect (%os-cpu)))))
      (m "userInfo" 1 (lambda (this args) (declare (ignore this args)) (%os-user-info)))
      (eng:data-prop o "constants" (eng:new-object))
      o)))

(register-node-builtin "os" #'build-node-os)
