;;;; catalog.lisp — single source of truth for CLI usage rows (help + man page).
;;;; Hard rule: man page content is derived from this catalog (and live --help).
;;;; Never hand-edit docs/man/clun.1 without regenerating from this data.

(in-package :clun.cli)

(defparameter *cli-usage-catalog*
  '(("clun <file>" . "run a .js/.mjs/.cjs/.json/.ts file")
    ("clun run" . "run a file or package.json script")
    ("clun -e / -p" . "evaluate code (print awaited result)")
    ("clun exec" . "execute a Clun shell script")
    ("clun install" . "install deps, or add package(s) + install")
    ("clun add" . "add package(s) (-d dev, -E exact) + install")
    ("clun remove" . "remove a dependency + reinstall")
    ("clun publish" . "pack + publish to npm (NPM_TOKEN / .npmrc)")
    ("clun build" . "production bundle (Clun.build / Bun.build)")
    ("clun fmt / lint" . "format or lint JS/TS/JSON/YAML/CSS")
    ("clun compile" . "single-file executable")
    ("clun tsc" . "structural TypeScript typecheck")
    ("clun test" . "run the test runner")
    ("clun update" . "verify and activate latest Release bundle"))
  "Usage synopsis rows shown by `clun --help` and `man clun`.")

(defparameter *cli-flag-catalog*
  '(("--cwd <dir>" . "set the working directory")
    ("--hot / --watch" . "soft-reload or hard-restart on change")
    ("--filter/-F <p>" . "monorepo package name or ./path filter")
    ("--workspaces" . "run a script across every workspace package")
    ("--parallel" . "concurrent filtered scripts (topo waves)")
    ("--concurrency N" . "max concurrent workspace scripts")
    ("--silent" . "suppress console.log/info/debug")
    ("--backtrace" . "Lisp backtrace on internal error")
    ("-v / --version" . "print the version")
    ("--update" . "same as clun update")
    ("--check-update" . "report whether a newer Release is available")
    ("-h / --help" . "print this help"))
  "Global flag rows shown by `clun --help` and `man clun`.")

;;; Subcommand tokens accepted by parse-cli-args — must appear in man page COMMANDS.
(defparameter *cli-subcommand-tokens*
  '("run" "test" "install" "add" "remove" "publish" "exec"
    "build" "compile" "fmt" "format" "lint" "x" "create" "init" "tsc" "typecheck"
    "update" "check-update" "help" "version")
  "Positional tokens recognized as commands (kept in sync with parse-cli-args).")

(defun write-manpage (stream version)
  "Write a groff man page for section 1 to STREAM for the given VERSION string."
  (format stream ".\\\" Generated from src/cli/catalog.lisp — do not hand-edit.~%")
  (format stream ".\\\" Regenerate: make man~%")
  (format stream ".TH CLUN 1 \"~a\" \"Clun ~a\" \"User Commands\"~%" version version)
  (format stream ".SH NAME~%")
  (format stream "clun \\- JavaScript/TypeScript runtime and toolkit in pure Common Lisp~%")
  (format stream ".SH SYNOPSIS~%")
  (format stream ".B clun~%")
  (format stream "[\\fIglobal-flags\\fR] \\fIcommand\\fR [\\fIargs\\fR]~%")
  (format stream ".br~%")
  (format stream ".B clun~%")
  (format stream "[\\fIglobal-flags\\fR] \\fIfile\\fR [\\fIargs\\fR]~%")
  (format stream ".SH DESCRIPTION~%")
  (format stream "Clun is a Bun-shaped JavaScript and TypeScript toolkit implemented entirely~%")
  (format stream "in pure Common Lisp: runtime, package manager, test runner, bundler, HTTP~%")
  (format stream "server, and related tooling. JavaScript is only what the user runs; Clun's~%")
  (format stream "implementation is not Node, V8, libuv, Rust, Zig, or C.~%")
  (format stream ".PP~%")
  (format stream "This page is generated from the same command catalog as~%")
  (format stream ".BR \"clun --help\"~%")
  (format stream "and must stay synchronized with live CLI behavior.~%")
  (format stream ".SH COMMANDS~%")
  (dolist (entry *cli-usage-catalog*)
    (format stream ".TP~%")
    (format stream ".B ~a~%" (car entry))
    (format stream "~a~%" (cdr entry)))
  (format stream ".SH OPTIONS~%")
  (dolist (entry *cli-flag-catalog*)
    (format stream ".TP~%")
    (format stream ".B ~a~%" (car entry))
    (format stream "~a~%" (cdr entry)))
  (format stream ".SH EXIT STATUS~%")
  (format stream ".TP~%")
  (format stream ".B 0~%")
  (format stream "Success.~%")
  (format stream ".TP~%")
  (format stream ".B 1~%")
  (format stream "Runtime or command error.~%")
  (format stream ".TP~%")
  (format stream ".B 2~%")
  (format stream "Usage error.~%")
  (format stream ".SH ENVIRONMENT~%")
  (format stream ".TP~%")
  (format stream ".B NO_COLOR~%")
  (format stream "Disable CLI color chrome when set.~%")
  (format stream ".TP~%")
  (format stream ".B CLUN_FORCE_COLOR~%")
  (format stream "Force CLI color chrome when set.~%")
  (format stream ".TP~%")
  (format stream ".B INSTALL_VERSION / CLUN_VERSION~%")
  (format stream "Used by the shell installer to pin a release tag.~%")
  (format stream ".SH FILES~%")
  (format stream ".TP~%")
  ;; ~~ is a literal tilde in FORMAT (paths like ~/.local must not be directives).
  (format stream ".I ~~/.local/bin/clun~%")
  (format stream "Default launcher symlink after install.~%")
  (format stream ".TP~%")
  (format stream ".I ${XDG_DATA_HOME:-~~/.local/share}/clun/releases/~%")
  (format stream "Versioned release trees.~%")
  (format stream ".TP~%")
  (format stream ".I ${XDG_DATA_HOME:-~~/.local/share}/man/man1/clun.1~%")
  (format stream "Installed man page (when using the standard installer).~%")
  (format stream ".SH SEE ALSO~%")
  (format stream ".BR clun (1)~%")
  (format stream "is the primary documentation entry. Online:~%")
  (format stream "https://clun.sh/ and https://github.com/theesfeld/clun~%")
  (format stream ".SH BUGS~%")
  (format stream "Report issues at https://github.com/theesfeld/clun/issues~%")
  (values))
