;;;; catalog.lisp — single source of truth for CLI usage rows (help + man page).
;;;; Hard rule: man page content is derived from this catalog (and live --help).
;;;; Never hand-edit docs/man/clun.1 without regenerating from this data.

(in-package :clun.cli)

;;; Catalog strings follow ASD-STE100 principles: short, active, one idea per line.
(defparameter *cli-usage-catalog*
  '(("clun <file>" . "Run a .js, .mjs, .cjs, .json, or .ts file.")
    ("clun run" . "Run a file or a package.json script.")
    ("clun -e / -p" . "Evaluate code. -p prints the result.")
    ("clun exec" . "Run a Clun shell script.")
    ("clun install" . "Install dependencies, or add packages and install.")
    ("clun add" . "Add packages (-d for dev, -E for exact) and install.")
    ("clun remove" . "Remove a dependency and install again.")
    ("clun publish" . "Pack and publish to npm (NPM_TOKEN or .npmrc).")
    ("clun build" . "Build a production bundle (Clun.build / Bun.build).")
    ("clun fmt / lint" . "Format or lint JS, TS, JSON, YAML, or CSS.")
    ("clun compile" . "Build a single-file executable.")
    ("clun tsc" . "Run structural TypeScript typecheck.")
    ("clun test" . "Run the test runner.")
    ("clun update" . "Verify and activate the latest Release bundle."))
  "Usage synopsis rows shown by `clun --help` and `man clun`.")

(defparameter *cli-flag-catalog*
  '(("--cwd <dir>" . "Set the working directory.")
    ("--hot / --watch" . "Reload on change (--hot soft, --watch hard restart).")
    ("--filter/-F <p>" . "Filter monorepo packages by name or ./path.")
    ("--workspaces" . "Run a script in every workspace package.")
    ("--parallel" . "Run filtered scripts in concurrent topo waves.")
    ("--concurrency N" . "Set max concurrent workspace scripts.")
    ("--silent" . "Suppress console.log, info, and debug.")
    ("--backtrace" . "Show a Lisp backtrace on internal error.")
    ("-v / --version" . "Print the version.")
    ("--update" . "Same as clun update.")
    ("--check-update" . "Report if a newer Release is available.")
    ("-h / --help" . "Print this help."))
  "Global flag rows shown by `clun --help` and `man clun`.")

;;; Subcommand tokens accepted by parse-cli-args — must appear in man page COMMANDS.
(defparameter *cli-subcommand-tokens*
  '("run" "test" "install" "add" "remove" "publish" "exec"
    "build" "compile" "fmt" "format" "lint" "x" "create" "init" "tsc" "typecheck"
    "update" "check-update" "help" "version")
  "Positional tokens recognized as commands (kept in sync with parse-cli-args).")

(defun write-manpage (stream version)
  "Write a groff man page for section 1 to STREAM for the given VERSION string."
  (format stream ".\\\" Generated from src/cli/catalog.lisp — do not hand-edit.~%")
  (format stream ".\\\" Regenerate: make man~%")
  (format stream ".TH CLUN 1 \"~a\" \"Clun ~a\" \"User Commands\"~%" version version)
  (format stream ".SH NAME~%")
  (format stream "clun \\- JavaScript and TypeScript toolkit in pure Common Lisp~%")
  (format stream ".SH SYNOPSIS~%")
  (format stream ".B clun~%")
  (format stream "[\\fIglobal-flags\\fR] \\fIcommand\\fR [\\fIargs\\fR]~%")
  (format stream ".br~%")
  (format stream ".B clun~%")
  (format stream "[\\fIglobal-flags\\fR] \\fIfile\\fR [\\fIargs\\fR]~%")
  (format stream ".SH DESCRIPTION~%")
  ;; ASD-STE100-style: short active sentences; one idea per sentence.
  (format stream "Clun is a JavaScript and TypeScript toolkit.~%")
  (format stream "The implementation is pure Common Lisp.~%")
  (format stream "Clun provides a runtime, package manager, test runner, bundler, HTTP server,~%")
  (format stream "and related tools.~%")
  (format stream "Command names and APIs follow Bun shape.~%")
  (format stream "JavaScript is only what the user runs.~%")
  (format stream "The Clun implementation is not Node, V8, libuv, Rust, Zig, or C.~%")
  (format stream ".PP~%")
  (format stream "This page uses the same command catalog as~%")
  (format stream ".BR \"clun --help\"~%")
  (format stream ".~%")
  (format stream "The man page must match live CLI behavior.~%")
  (format stream "Regenerate with~%")
  (format stream ".B make man~%")
  (format stream "after you change the catalog.~%")
  (format stream ".SH COMMANDS~%")
  (dolist (entry *cli-usage-catalog*)
    (format stream ".TP~%")
    (format stream ".B ~a~%" (car entry))
    (format stream "~a~%" (cdr entry)))
  (format stream ".SH OPTIONS~%")
  (dolist (entry *cli-flag-catalog*)
    (format stream ".TP~%")
    (format stream ".B ~a~%" (car entry))
    (format stream "~a~%" (cdr entry)))
  (format stream ".SH EXIT STATUS~%")
  (format stream ".TP~%")
  (format stream ".B 0~%")
  (format stream "Success.~%")
  (format stream ".TP~%")
  (format stream ".B 1~%")
  (format stream "Runtime or command error.~%")
  (format stream ".TP~%")
  (format stream ".B 2~%")
  (format stream "Usage error.~%")
  (format stream ".SH ENVIRONMENT~%")
  (format stream ".TP~%")
  (format stream ".B NO_COLOR~%")
  (format stream "If set, disable CLI color.~%")
  (format stream ".TP~%")
  (format stream ".B CLUN_FORCE_COLOR~%")
  (format stream "If set, force CLI color.~%")
  (format stream ".TP~%")
  (format stream ".B INSTALL_VERSION / CLUN_VERSION~%")
  (format stream "Pin the install release tag for the shell installer.~%")
  (format stream ".SH FILES~%")
  (format stream ".TP~%")
  ;; ~~ is a literal tilde in FORMAT (paths like ~/.local must not be directives).
  (format stream ".I ~~/.local/bin/clun~%")
  (format stream "Default launcher after install.~%")
  (format stream ".TP~%")
  (format stream ".I ${XDG_DATA_HOME:-~~/.local/share}/clun/releases/~%")
  (format stream "Versioned release trees.~%")
  (format stream ".TP~%")
  (format stream ".I ${XDG_DATA_HOME:-~~/.local/share}/man/man1/clun.1~%")
  (format stream "Installed man page (standard installer).~%")
  (format stream ".SH NOTES~%")
  (format stream "Installable default release is the verified boundary in the release ledger.~%")
  (format stream "Source may be a later candidate. Do not assume a source version is installable~%")
  (format stream "until a matching GitHub Release with assets exists.~%")
  (format stream ".SH SEE ALSO~%")
  (format stream "Online documentation:~%")
  (format stream "https://clun.sh/ and https://github.com/theesfeld/clun~%")
  (format stream ".SH BUGS~%")
  (format stream "Report issues at https://github.com/theesfeld/clun/issues~%")
  (values))
