;;;; builtins-string.lisp — String.prototype breadth + String statics (Phase 04,
;;;; §22.1). Code-unit-exact over CL strings (one char = one UTF-16 code unit).
;;;; RegExp-taking overloads (match/matchAll/search, regexp split/replace) defer to
;;;; Phase 10; the string-pattern paths land here.

(in-package :clun.engine)

(defconstant +max-js-string-length+ (expt 2 28)
  "Cap on strings clun will materialize (268M code units ≈ 1 GiB at 4 bytes/char);
beyond this padStart/padEnd/repeat throw RangeError('Invalid string length') rather
than exhausting the host heap. Real engines cap near 2^30; we stay under the heap.")

(defun %this-str (this) (to-string (require-object-coercible this)))

(defun %clamp (n lo hi) (max lo (min hi n)))

(defun %rel-index (v len)
  "ToIntegerOrInfinity V, resolving a negative index against LEN, clamped to [0,len]."
  (let ((n (to-integer-or-infinity v)))
    (cond ((js-infinite-p n) (if (plusp n) len 0))
          ((minusp n) (max 0 (+ len (truncate n))))
          (t (min len (truncate n))))))

(defun %get-substitution (matched str position replacement)
  "Apply $ patterns in REPLACEMENT for a string-pattern match (no captures)."
  (with-output-to-string (out)
    (let ((i 0) (n (length replacement)) (tail (+ position (length matched))))
      (loop while (< i n) do
        (let ((c (char replacement i)))
          (if (and (char= c #\$) (< (1+ i) n))
              (let ((d (char replacement (1+ i))))
                (case d
                  (#\$ (write-char #\$ out) (incf i 2))
                  (#\& (write-string matched out) (incf i 2))
                  (#\` (write-string (subseq str 0 position) out) (incf i 2))
                  (#\' (write-string (subseq str tail) out) (incf i 2))
                  (t (write-char c out) (incf i))))
              (progn (write-char c out) (incf i))))))))

(defun %string-split (s sep lim)
  (let ((result '()) (slen (length s)) (seplen (length sep)))
    (when (zerop lim) (return-from %string-split (new-array '())))
    (when (zerop slen)
      (return-from %string-split (new-array (if (zerop seplen) '() (list "")))))
    (when (zerop seplen)
      (return-from %string-split
        (new-array (loop for i below (min slen lim) collect (string (char s i))))))
    (let ((start 0) (pos 0))
      (loop
        (let ((found (search sep s :start2 pos)))
          (if (or (null found) (> (+ found seplen) slen))
              (progn (push (subseq s start) result) (return))
              (progn (push (subseq s start found) result)
                     (when (>= (length result) lim) (return))
                     (setf start (+ found seplen) pos (+ found seplen))))))
      (let ((lst (nreverse result)))
        (new-array (subseq lst 0 (min (length lst) lim)))))))

(defun %bootstrap-string-extra ()
  (let ((sp (intrinsic :string-prototype)) (sc (intrinsic :string-constructor)))
    (macrolet ((m (name arity &body body) `(install-method sp ,name ,arity ,@body)))
      (m "at" 1 (lambda (this args)
                  (let* ((s (%this-str this)) (len (length s)) (n (%int (arg args 0)))
                         (i (if (minusp n) (+ len n) n)))
                    (if (and (<= 0 i) (< i len)) (string (char s i)) +undefined+))))
      (m "charAt" 1 (lambda (this args)
                      (let* ((s (%this-str this)) (i (%int (arg args 0))))
                        (if (and (<= 0 i) (< i (length s))) (string (char s i)) ""))))
      (m "charCodeAt" 1 (lambda (this args)
                          (let* ((s (%this-str this)) (i (%int (arg args 0))))
                            (if (and (<= 0 i) (< i (length s))) (coerce (char-code (char s i)) 'double-float) *js-nan*))))
      (m "codePointAt" 1 (lambda (this args)
                           (let* ((s (%this-str this)) (i (%int (arg args 0))) (len (length s)))
                             (if (not (and (<= 0 i) (< i len))) +undefined+
                                 (let ((c (char-code (char s i))))
                                   (if (and (high-surrogate-p c) (< (1+ i) len) (low-surrogate-p (char-code (char s (1+ i)))))
                                       (coerce (+ #x10000 (ash (- c #xD800) 10) (- (char-code (char s (1+ i))) #xDC00)) 'double-float)
                                       (coerce c 'double-float)))))))
      (m "indexOf" 1 (lambda (this args)
                       (let* ((s (%this-str this)) (sub (to-string (arg args 0)))
                              (pos (%clamp (%int (arg args 1)) 0 (length s))))
                         (coerce (or (search sub s :start2 pos) -1) 'double-float))))
      (m "lastIndexOf" 1 (lambda (this args)
                           (let* ((s (%this-str this)) (sub (to-string (arg args 0))) (len (length s))
                                  (posn (to-number (arg args 1)))
                                  ;; NaN position (incl. undefined) -> search the whole string.
                                  (start (if (js-nan-p posn) len (max 0 (min (%int (arg args 1)) len))))
                                  (end2 (min (+ start (length sub)) len)))
                             (coerce (or (search sub s :from-end t :end2 end2) -1) 'double-float))))
      (m "includes" 1 (lambda (this args)
                        (let* ((s (%this-str this)) (sub (to-string (arg args 0)))
                               (pos (%clamp (%int (arg args 1)) 0 (length s))))
                          (js-boolean (search sub s :start2 pos)))))
      (m "startsWith" 1 (lambda (this args)
                          (let* ((s (%this-str this)) (sub (to-string (arg args 0)))
                                 (pos (%clamp (%int (arg args 1)) 0 (length s))))
                            (js-boolean (and (<= (+ pos (length sub)) (length s))
                                             (string= sub s :start2 pos :end2 (+ pos (length sub))))))))
      (m "endsWith" 1 (lambda (this args)
                        (let* ((s (%this-str this)) (sub (to-string (arg args 0)))
                               (end (if (js-undefined-p (arg args 1)) (length s)
                                        (%clamp (%int (arg args 1)) 0 (length s)))))
                          (js-boolean (and (>= (- end (length sub)) 0)
                                           (string= sub s :start2 (- end (length sub)) :end2 end))))))
      (m "slice" 2 (lambda (this args)
                     (let* ((s (%this-str this)) (len (length s))
                            (start (%rel-index (arg args 0) len))
                            (end (if (js-undefined-p (arg args 1)) len (%rel-index (arg args 1) len))))
                       (if (< start end) (subseq s start end) ""))))
      (m "substring" 2 (lambda (this args)
                         (let* ((s (%this-str this)) (len (length s))
                                (a (%clamp (%int (arg args 0)) 0 len))
                                (b (if (js-undefined-p (arg args 1)) len (%clamp (%int (arg args 1)) 0 len))))
                           (subseq s (min a b) (max a b)))))
      (m "substr" 2 (lambda (this args)
                      (let* ((s (%this-str this)) (len (length s))
                             (start (let ((n (%int (arg args 0)))) (if (minusp n) (max 0 (+ len n)) (min n len))))
                             (length-arg (if (js-undefined-p (arg args 1)) len (%int (arg args 1))))
                             (end (%clamp (+ start (max 0 length-arg)) 0 len)))
                        (if (< start end) (subseq s start end) ""))))
      (m "toLowerCase" 0 (lambda (this args) (declare (ignore args)) (string-downcase (%this-str this))))
      (m "toUpperCase" 0 (lambda (this args) (declare (ignore args)) (string-upcase (%this-str this))))
      (m "toLocaleLowerCase" 0 (lambda (this args) (declare (ignore args)) (string-downcase (%this-str this))))
      (m "toLocaleUpperCase" 0 (lambda (this args) (declare (ignore args)) (string-upcase (%this-str this))))
      (m "trim" 0 (lambda (this args) (declare (ignore args)) (%trim-js-whitespace (%this-str this))))
      (m "trimStart" 0 (lambda (this args) (declare (ignore args))
                         (let ((s (%this-str this)) (i 0)) (loop while (and (< i (length s)) (%js-whitespace-p (char s i))) do (incf i)) (subseq s i))))
      (m "trimEnd" 0 (lambda (this args) (declare (ignore args))
                       (let* ((s (%this-str this)) (e (length s))) (loop while (and (> e 0) (%js-whitespace-p (char s (1- e)))) do (decf e)) (subseq s 0 e))))
      (m "padStart" 1 (lambda (this args) (%string-pad this args t)))
      (m "padEnd" 1 (lambda (this args) (%string-pad this args nil)))
      (m "repeat" 1 (lambda (this args)
                      (let* ((s (%this-str this)) (n (to-integer-or-infinity (arg args 0))))
                        (when (or (minusp n) (js-infinite-p n)) (throw-range-error "Invalid count value"))
                        (when (> (* (truncate n) (length s)) +max-js-string-length+)
                          (throw-range-error "Invalid string length"))
                        (with-output-to-string (o) (dotimes (i (truncate n)) (write-string s o))))))
      (m "concat" 1 (lambda (this args)
                      (with-output-to-string (o) (write-string (%this-str this) o) (dolist (a args) (write-string (to-string a) o)))))
      (m "split" 2 (lambda (this args)
                     (require-object-coercible this)
                     (let ((sep (arg args 0)) (lim-arg (arg args 1)))
                       (let ((s (to-string this))
                             (lim (if (js-undefined-p lim-arg) #xFFFFFFFF (double->uint32 (to-number lim-arg)))))
                         (if (js-undefined-p sep) (new-array (list s))
                             (%string-split s (to-string sep) lim))))))
      (m "replace" 2 (lambda (this args) (%string-replace this (arg args 0) (arg args 1) nil)))
      (m "replaceAll" 2 (lambda (this args) (%string-replace this (arg args 0) (arg args 1) t)))
      (m "localeCompare" 1 (lambda (this args)
                             (let ((a (%this-str this)) (b (to-string (arg args 0))))
                               (cond ((string< a b) -1d0) ((string> a b) 1d0) (t 0d0)))))
      (m "normalize" 0 (lambda (this args) (declare (ignore args)) (%this-str this))))
    ;; String statics
    (install-method sc "fromCharCode" 1
      (lambda (this args) (declare (ignore this))
        (coerce (mapcar (lambda (a) (code-char (logand (double->uint32 (to-number a)) #xFFFF))) args) 'string)))
    (install-method sc "fromCodePoint" 1
      (lambda (this args) (declare (ignore this))
        (let ((out (make-array 8 :element-type 'character :adjustable t :fill-pointer 0)))
          (dolist (a args)
            (let ((n (to-number a)))
              (unless (and (js-finite-p n) (= n (ftruncate n)) (<= 0 n #x10FFFF))
                (throw-range-error (format nil "Invalid code point ~a" (number->js-string n))))
              (%push-code-point (truncate n) out)))
          (coerce out '(simple-array character (*))))))
    (install-method sc "raw" 1
      (lambda (this args) (declare (ignore this))
        (let* ((cooked (to-object (arg args 0))) (raw (to-object (js-get cooked "raw")))
               (len (length-of-array-like raw)) (subs (rest args)))
          (with-output-to-string (o)
            (dotimes (i len)
              (write-string (to-string (js-getv raw (princ-to-string i))) o)
              (when (and (< (1+ i) len) (< i (length subs)))
                (write-string (to-string (nth i subs)) o)))))))))

(defun %string-pad (this args start)
  (let* ((s (%this-str this)) (target (%int (arg args 0)))
         (filler (if (js-undefined-p (arg args 1)) " " (to-string (arg args 1)))))
    (when (> target +max-js-string-length+) (throw-range-error "Invalid string length"))
    (if (or (<= target (length s)) (zerop (length filler))) s
        (let* ((needed (- target (length s)))
               (full (with-output-to-string (o) (dotimes (i (ceiling needed (length filler))) (write-string filler o))))
               (pad (subseq full 0 needed)))
          (if start (concatenate 'string pad s) (concatenate 'string s pad))))))

(defun %string-replace (this search-value replace-value all)
  (require-object-coercible this)
  (let* ((s (to-string this)) (pat (to-string search-value))
         (fnp (callable-p replace-value))
         (repl (if fnp replace-value (to-string replace-value)))
         (slen (length s)) (plen (length pat)))
    (flet ((emit (out matched pos)
             (if fnp
                 (write-string (to-string (js-call repl +undefined+ (list matched (coerce pos 'double-float) s))) out)
                 (write-string (%get-substitution matched s pos repl) out))))
      (with-output-to-string (out)
        (cond
          ((zerop plen)                         ; empty pattern
           (emit out "" 0)
           (if all
               (dotimes (i slen) (write-char (char s i) out) (emit out "" (1+ i)))
               (write-string s out)))
          (t (let ((pos 0))
               (loop
                 (let ((found (search pat s :start2 pos)))
                   (cond
                     ((null found) (write-string (subseq s pos) out) (return))
                     (t (write-string (subseq s pos found) out)
                        (emit out pat found)
                        (setf pos (+ found plen))
                        (unless all (write-string (subseq s pos) out) (return)))))))))))))
