;;;; builtins-array.lisp — Array.prototype breadth (ES2017) + Array statics
;;;; (PLAN.md Phase 04, §23.1). Generic over array-likes via the object API; a
;;;; stable merge sort for Array.prototype.sort. Extends the Phase 03 Array set.

(in-package :clun.engine)

(declaim (inline %aidx))
(defun %aidx (i) (princ-to-string i))
(defun %alen (o) (length-of-array-like o))
(defun %aget (o i) (js-getv o (%aidx i)))
(defun %aset (o i v) (js-set o (%aidx i) v t))
(defun %ahas (o i) (has-property o (%aidx i)))
(defun %adel (o i) (jm-delete o (%aidx i)))
(defun %aset-len (o n) (js-set o "length" (coerce n 'double-float) t))

(defun %array-species-new (n) (js-make-array (intrinsic :array-prototype) n))

(defun %to-array-list (o len)
  (loop for i below len collect (%aget o i)))

(defun %array-sort-less (a b comparefn)
  (cond ((js-undefined-p a) nil)
        ((js-undefined-p b) t)
        (comparefn (let ((r (to-number (js-call comparefn +undefined+ (list a b)))))
                     (and (not (js-nan-p r)) (< r 0))))   ; NaN -> treat as +0 (not less)
        (t (string< (to-string a) (to-string b)))))

(defun %stable-sort-list (items comparefn)
  (stable-sort (copy-list items) (lambda (a b) (%array-sort-less a b comparefn))))

(defun %array-flatten (target source depth)
  "Append SOURCE's elements to TARGET list (reversed accumulator returned)."
  (let ((len (%alen source)) (acc target))
    (dotimes (i len acc)
      (when (%ahas source i)
        (let ((e (%aget source i)))
          (if (and (> depth 0) (is-array e))
              (setf acc (%array-flatten acc e (1- depth)))
              (push e acc)))))))

(defun %array-from (items mapfn this-arg)
  (when (and mapfn (not (callable-p mapfn)))
    (throw-type-error "Array.from mapper is not a function"))
  (let ((iter-fn (get-method items (well-known :iterator))))
    (if (not (js-undefined-p iter-fn))
        (let ((record (get-iterator-record items iter-fn))
              (vals '())
              (i 0))
          (loop
            (multiple-value-bind (value done) (iterator-step-value record)
              (when done
                (return (new-array (nreverse vals))))
              (let ((mapped
                      (call-with-iterator-close-on-abrupt
                       record
                       (lambda ()
                         (if mapfn
                             (js-call mapfn this-arg
                                      (list value (coerce i 'double-float)))
                             value)))))
                (push mapped vals)
                (incf i)))))
        (let* ((o (to-object items)) (len (%alen o)))
          (new-array (loop for i below len
                           collect (let ((v (%aget o i))) (if mapfn (js-call mapfn this-arg (list v (coerce i 'double-float))) v))))))))

(defun %bootstrap-array-extra ()
  (let ((ap (intrinsic :array-prototype)) (ac (intrinsic :array-constructor)))
    (macrolet ((m (name arity &body body) `(install-method ap ,name ,arity ,@body)))
      (m "at" 1 (lambda (this args)
                  (let* ((o (to-object this)) (len (%alen o)) (n (%int (arg args 0)))
                         (i (if (minusp n) (+ len n) n)))
                    (if (and (<= 0 i) (< i len)) (%aget o i) +undefined+))))
      (m "shift" 0 (lambda (this args) (declare (ignore args))
                     (let* ((o (to-object this)) (len (%alen o)))
                       (if (zerop len) (progn (%aset-len o 0) +undefined+)
                           (let ((first (%aget o 0)))
                             (loop for i from 1 below len do (if (%ahas o i) (%aset o (1- i) (%aget o i)) (%adel o (1- i))))
                             (%adel o (1- len)) (%aset-len o (1- len)) first)))))
      (m "unshift" 1 (lambda (this args)
                       (let* ((o (to-object this)) (len (%alen o)) (k (length args)))
                         (loop for i from (1- len) downto 0 do (if (%ahas o i) (%aset o (+ i k) (%aget o i)) (%adel o (+ i k))))
                         (loop for v in args for i from 0 do (%aset o i v))
                         (%aset-len o (+ len k)) (coerce (+ len k) 'double-float))))
      (m "reverse" 0 (lambda (this args) (declare (ignore args))
                       (let* ((o (to-object this)) (len (%alen o)))
                         (dotimes (i (floor len 2))
                           (let ((j (- len 1 i)) (hi (%ahas o i)) (hj (%ahas o (- len 1 i))))
                             (let ((vi (and hi (%aget o i))) (vj (and hj (%aget o j))))
                               (if hj (%aset o i vj) (%adel o i))
                               (if hi (%aset o j vi) (%adel o j)))))
                         o)))
      (m "fill" 1 (lambda (this args)
                    (let* ((o (to-object this)) (len (%alen o)) (v (arg args 0))
                           (start (%rel-index (arg args 1) len))
                           (end (if (js-undefined-p (arg args 2)) len (%rel-index (arg args 2) len))))
                      (loop for i from start below end do (%aset o i v)) o)))
      (m "copyWithin" 2 (lambda (this args)
                          (let* ((o (to-object this)) (len (%alen o))
                                 (target (%rel-index (arg args 0) len))
                                 (start (%rel-index (arg args 1) len))
                                 (end (if (js-undefined-p (arg args 2)) len (%rel-index (arg args 2) len)))
                                 (count (min (- end start) (- len target)))
                                 (vals (loop for i from start below (+ start (max 0 count)) collect (cons (%ahas o i) (%aget o i)))))
                            (loop for pair in vals for i from target
                                  do (if (car pair) (%aset o i (cdr pair)) (%adel o i)))
                            o)))
      (m "lastIndexOf" 1 (lambda (this args)
                           (let* ((o (to-object this)) (len (%alen o)) (target (arg args 0)))
                             (coerce (or (loop for i from (1- len) downto 0
                                               when (and (%ahas o i) (js-strict-eq (%aget o i) target)) do (return i)) -1) 'double-float))))
      (m "find" 1 (lambda (this args) (%array-find this args :value nil)))
      (m "findIndex" 1 (lambda (this args) (%array-find this args :index nil)))
      (m "findLast" 1 (lambda (this args) (%array-find this args :value t)))
      (m "findLastIndex" 1 (lambda (this args) (%array-find this args :index t)))
      (m "every" 1 (lambda (this args)
                     (let* ((o (to-object this)) (len (%alen o)) (f (arg args 0)) (that (arg args 1)))
                       (dotimes (i len +true+)
                         (when (and (%ahas o i) (not (js-truthy (js-call f that (list (%aget o i) (coerce i 'double-float) o)))))
                           (return +false+))))))
      (m "some" 1 (lambda (this args)
                    (let* ((o (to-object this)) (len (%alen o)) (f (arg args 0)) (that (arg args 1)))
                      (dotimes (i len +false+)
                        (when (and (%ahas o i) (js-truthy (js-call f that (list (%aget o i) (coerce i 'double-float) o))))
                          (return +true+))))))
      (m "filter" 1 (lambda (this args)
                      (let* ((o (to-object this)) (len (%alen o)) (f (arg args 0)) (that (arg args 1)) (out '()))
                        (dotimes (i len) (when (%ahas o i)
                                           (let ((v (%aget o i)))
                                             (when (js-truthy (js-call f that (list v (coerce i 'double-float) o))) (push v out)))))
                        (new-array (nreverse out)))))
      (m "reduce" 1 (lambda (this args) (%array-reduce this args nil)))
      (m "reduceRight" 1 (lambda (this args) (%array-reduce this args t)))
      (m "sort" 1 (lambda (this args)
                    (let* ((o (to-object this)) (len (%alen o)) (comparefn (arg args 0)))
                      (unless (or (js-undefined-p comparefn) (callable-p comparefn)) (throw-type-error "comparator is not a function"))
                      (let* ((present (loop for i below len when (%ahas o i) collect (%aget o i)))
                             (npresent (length present))
                             (sorted (%stable-sort-list present (if (js-undefined-p comparefn) nil comparefn))))
                        (loop for v in sorted for i from 0 do (%aset o i v))
                        (loop for i from npresent below len do (%adel o i))
                        o))))
      (m "splice" 2 (lambda (this args) (%array-splice this args)))
      (m "flat" 0 (lambda (this args)
                    (let* ((o (to-object this))
                           (depth (if (js-undefined-p (arg args 0)) 1 (%int (arg args 0)))))
                      (new-array (nreverse (%array-flatten '() o depth))))))
      (m "flatMap" 1 (lambda (this args)
                       (let* ((o (to-object this)) (len (%alen o)) (f (arg args 0)) (that (arg args 1)) (acc '()))
                         (dotimes (i len)
                           (when (%ahas o i)
                             (let ((v (js-call f that (list (%aget o i) (coerce i 'double-float) o))))
                               (if (is-array v) (setf acc (%array-flatten acc v 0)) (push v acc)))))
                         (new-array (nreverse acc))))))
    (install-method ac "from" 1
      (lambda (this args) (declare (ignore this))
        (%array-from (arg args 0) (let ((mf (arg args 1))) (if (js-undefined-p mf) nil mf)) (arg args 2))))))

(defun %array-find (this args mode from-end)
  (let* ((o (to-object this)) (len (%alen o)) (f (arg args 0)) (that (arg args 1)))
    (flet ((check (i) (js-truthy (js-call f that (list (%aget o i) (coerce i 'double-float) o)))))
      (if from-end
          (loop for i from (1- len) downto 0 when (check i)
                do (return-from %array-find (if (eq mode :value) (%aget o i) (coerce i 'double-float))))
          (dotimes (i len) (when (check i)
                             (return-from %array-find (if (eq mode :value) (%aget o i) (coerce i 'double-float)))))))
    (if (eq mode :value) +undefined+ -1d0)))

(defun %array-splice (this args)
  (let* ((o (to-object this)) (len (%alen o))
         (start (%rel-index (arg args 0) len))
         (insert (if (>= (length args) 2) (cddr args) '()))
         (del (cond ((< (length args) 1) 0)
                    ((< (length args) 2) (- len start))
                    (t (max 0 (min (%int (arg args 1)) (- len start))))))
         (removed (loop for i below del when (%ahas o (+ start i)) collect (cons i (%aget o (+ start i)))))
         (result (%array-species-new del))
         (ins (length insert)))
    (dolist (pair removed) (create-data-property result (%aidx (car pair)) (cdr pair)))
    (%aset-len result del)
    (cond
      ((< ins del)                              ; shrink: shift tail left
       (loop for i from start below (- len del)
             do (if (%ahas o (+ i del)) (%aset o (+ i ins) (%aget o (+ i del))) (%adel o (+ i ins))))
       (loop for i from (- len (- del ins)) below len do (%adel o i)))
      ((> ins del)                              ; grow: shift tail right
       (loop for i from (- len del) above start
             do (let ((from (+ i del -1)) (to (+ i ins -1)))
                  (if (%ahas o from) (%aset o to (%aget o from)) (%adel o to))))))
    (loop for v in insert for i from start do (%aset o i v))
    (%aset-len o (+ (- len del) ins))
    result))

(defun %array-reduce (this args right)
  (let* ((o (to-object this)) (len (%alen o)) (f (arg args 0)))
    (unless (callable-p f) (throw-type-error "reduce callback is not a function"))
    (let ((acc +undefined+) (have (>= (length args) 2)))
      (when have (setf acc (arg args 1)))
      (flet ((visit (i)
               (when (%ahas o i)
                 (if have
                     (setf acc (js-call f +undefined+
                                        (list acc (%aget o i) (coerce i 'double-float) o)))
                     (setf acc (%aget o i) have t)))))
        (if right
            (loop for i = (1- len) then (1- i)
                  while (>= i 0) do (visit i))
            (loop for i below len do (visit i))))
      (unless have (throw-type-error "Reduce of empty array with no initial value"))
      acc)))
