;;;; noncrypto-hash.lisp -- exact integer algorithms behind Clun.hash.
;;;;
;;;; The constants and algorithm shapes follow the public reference definitions
;;;; frozen by Bun c1076ce95e. All arithmetic is explicitly reduced to the
;;;; algorithm word size so results do not depend on the host word size.

(in-package :clun.hash)

(declaim (inline %u32 %u64 %mul32 %mul64 %rotl32 %rotr32 %rotl64 %rotr64
                 %read32le %read64le %mul-fold64))

(defconstant +u32-mask+ #xffffffff)
(defconstant +u64-mask+ #xffffffffffffffff)

(defun %u32 (x) (logand x +u32-mask+))
(defun %u64 (x) (logand x +u64-mask+))
(defun %mul32 (a b) (%u32 (* a b)))
(defun %mul64 (a b) (%u64 (* a b)))
(defun %rotl32 (x count)
  (let* ((n (mod count 32)) (v (%u32 x)))
    (%u32 (logior (ash v n) (ash v (- n 32))))))
(defun %rotr32 (x count) (%rotl32 x (- count)))
(defun %rotl64 (x count)
  (let* ((n (mod count 64)) (v (%u64 x)))
    (%u64 (logior (ash v n) (ash v (- n 64))))))
(defun %rotr64 (x count) (%rotl64 x (- count)))

(defun %read32le (bytes offset)
  (logior (aref bytes offset)
          (ash (aref bytes (+ offset 1)) 8)
          (ash (aref bytes (+ offset 2)) 16)
          (ash (aref bytes (+ offset 3)) 24)))

(defun %read64le (bytes offset)
  (logior (%read32le bytes offset)
          (ash (%read32le bytes (+ offset 4)) 32)))

(defun %write64le (bytes offset value)
  (dotimes (i 8 bytes)
    (setf (aref bytes (+ offset i)) (ldb (byte 8 (* i 8)) value))))

(defun %swap32 (value)
  (let ((x (%u32 value)))
    (logior (ash (ldb (byte 8 0) x) 24)
            (ash (ldb (byte 8 8) x) 16)
            (ash (ldb (byte 8 16) x) 8)
            (ldb (byte 8 24) x))))

(defun %swap64 (value)
  (let ((x (%u64 value)) (out 0))
    (dotimes (i 8 out)
      (setf out (logior (ash out 8) (ldb (byte 8 (* i 8)) x))))))

(defun %mul-fold64 (a b)
  (let ((product (* (%u64 a) (%u64 b))))
    (%u64 (logxor product (ash product -64)))))

(defun %simple-octets (bytes)
  (unless (typep bytes '(vector (unsigned-byte 8)))
    (error 'type-error :datum bytes :expected-type '(vector (unsigned-byte 8))))
  (if (typep bytes '(simple-array (unsigned-byte 8) (*)))
      bytes
      (coerce bytes '(simple-array (unsigned-byte 8) (*)))))

;;; Adler-32 / CRC-32 ----------------------------------------------------------

(defun adler32 (bytes &optional seed)
  (declare (ignore seed))
  (let ((s1 1) (s2 0) (n 0) (input (%simple-octets bytes)))
    ;; Reducing every 5,552 bytes is the zlib bound that keeps both sums small.
    (loop for byte across input
          do (incf s1 byte)
             (incf s2 s1)
             (incf n)
             (when (= n 5552)
               (setf s1 (mod s1 65521)
                     s2 (mod s2 65521)
                     n 0)))
    (logior (mod s1 65521) (ash (mod s2 65521) 16))))

(defparameter +crc32-table+
  (load-time-value
   (let ((table (make-array 256 :element-type '(unsigned-byte 32))))
     (dotimes (n 256 table)
       (let ((c n))
         (dotimes (k 8)
           (setf c (if (oddp c)
                       (logxor #xedb88320 (ash c -1))
                       (ash c -1))))
         (setf (aref table n) c))))
  t))

(defun crc32 (bytes &optional (seed 0))
  (let ((crc (logxor (%u32 seed) +u32-mask+)))
    (loop for byte across (%simple-octets bytes)
          do (setf crc
                   (logxor (aref +crc32-table+ (logand (logxor crc byte) #xff))
                           (ash crc -8))))
    (%u32 (logxor crc +u32-mask+))))

;;; MurmurHash ----------------------------------------------------------------

(defconstant +murmur-default-seed+ #xc70f6907)

(defun %fmix32 (h)
  (setf h (%u32 (logxor h (ash h -16)))
        h (%mul32 h #x85ebca6b)
        h (%u32 (logxor h (ash h -13)))
        h (%mul32 h #xc2b2ae35))
  (%u32 (logxor h (ash h -16))))

(defun murmur32v2 (bytes &optional (seed 0))
  (let* ((input (%simple-octets bytes))
         (length (length input))
         (h (%u32 (logxor seed length)))
         (offset 0)
         (m #x5bd1e995))
    (loop while (<= (+ offset 4) length)
          for k = (%read32le input offset)
          do (setf k (%mul32 k m)
                   k (%u32 (logxor k (ash k -24)))
                   k (%mul32 k m)
                   h (%u32 (logxor (%mul32 h m) k)))
             (incf offset 4))
    (case (- length offset)
      (3 (setf h (logxor h (ash (aref input (+ offset 2)) 16)))
         (setf h (logxor h (ash (aref input (+ offset 1)) 8)))
         (setf h (logxor h (aref input offset)))
         (setf h (%mul32 h m)))
      (2 (setf h (logxor h (ash (aref input (+ offset 1)) 8)))
         (setf h (logxor h (aref input offset)))
         (setf h (%mul32 h m)))
      (1 (setf h (%mul32 (logxor h (aref input offset)) m))))
    (setf h (%u32 (logxor h (ash h -13)))
          h (%mul32 h m))
    (%u32 (logxor h (ash h -15)))))

(defun murmur64v2 (bytes &optional (seed 0))
  (let* ((input (%simple-octets bytes))
         (length (length input))
         (m #xc6a4a7935bd1e995)
         (h (%u64 (logxor seed (%mul64 length m))))
         (offset 0))
    (loop while (<= (+ offset 8) length)
          for k = (%read64le input offset)
          do (setf k (%mul64 k m)
                   k (%u64 (logxor k (ash k -47)))
                   k (%mul64 k m)
                   h (%mul64 (logxor h k) m))
             (incf offset 8))
    (let ((tail 0))
      (loop for i from offset below length
            for shift from 0 by 8
            do (setf tail (logior tail (ash (aref input i) shift))))
      (when (< offset length)
        (setf h (%mul64 (logxor h tail) m))))
    (setf h (%u64 (logxor h (ash h -47)))
          h (%mul64 h m))
    (%u64 (logxor h (ash h -47)))))

(defun murmur32v3 (bytes &optional (seed 0))
  (let* ((input (%simple-octets bytes))
         (length (length input))
         (h (%u32 seed))
         (offset 0)
         (c1 #xcc9e2d51)
         (c2 #x1b873593))
    (loop while (<= (+ offset 4) length)
          for k = (%read32le input offset)
          do (setf k (%mul32 k c1)
                   k (%rotl32 k 15)
                   k (%mul32 k c2)
                   h (%u32 (logxor h k))
                   h (%rotl32 h 13)
                   h (%u32 (+ (%mul32 h 5) #xe6546b64)))
             (incf offset 4))
    (let ((k 0))
      (case (- length offset)
        (3 (setf k (logior (ash (aref input (+ offset 2)) 16)
                            (ash (aref input (+ offset 1)) 8)
                            (aref input offset))))
        (2 (setf k (logior (ash (aref input (+ offset 1)) 8)
                            (aref input offset))))
        (1 (setf k (aref input offset))))
      (unless (zerop k)
        (setf k (%mul32 k c1)
              k (%rotl32 k 15)
              k (%mul32 k c2)
              h (%u32 (logxor h k)))))
    (%fmix32 (logxor h length))))

;;; RapidHash and wyhash -------------------------------------------------------

(defparameter +rapid-secret+
  #(#x2d358dccaa6c78a5 #x8bb84b93962eacc9 #x4b33a62ed433d4a3))

(defun rapidhash (bytes &optional (seed 0))
  (let* ((input (%simple-octets bytes))
         (length (length input))
         (s0 (%u64 (logxor seed
                           (%mul-fold64 (logxor seed (aref +rapid-secret+ 0))
                                        (aref +rapid-secret+ 1))
                           length)))
         (s1 s0) (s2 s0) (offset 0) (remaining length) (a 0) (b 0))
    (if (<= length 16)
        (cond
          ((>= length 4)
           (let* ((d (ash (logand length 24) (- (ash length -3))))
                  (e (- length 4)))
             (setf a (logior (ash (%read32le input 0) 32) (%read32le input e))
                   b (logior (ash (%read32le input d) 32) (%read32le input (- e d))))))
          ((plusp length)
           (setf a (logior (ash (aref input 0) 56)
                           (ash (aref input (ash length -1)) 32)
                           (aref input (1- length))))))
        (progn
          (when (> length 48)
            (loop while (>= remaining 96)
                  do (setf s0 (%mul-fold64
                               (logxor (%read64le input offset) (aref +rapid-secret+ 0))
                               (logxor (%read64le input (+ offset 8)) s0))
                           s1 (%mul-fold64
                               (logxor (%read64le input (+ offset 16)) (aref +rapid-secret+ 1))
                               (logxor (%read64le input (+ offset 24)) s1))
                           s2 (%mul-fold64
                               (logxor (%read64le input (+ offset 32)) (aref +rapid-secret+ 2))
                               (logxor (%read64le input (+ offset 40)) s2))
                           s0 (%mul-fold64
                               (logxor (%read64le input (+ offset 48)) (aref +rapid-secret+ 0))
                               (logxor (%read64le input (+ offset 56)) s0))
                           s1 (%mul-fold64
                               (logxor (%read64le input (+ offset 64)) (aref +rapid-secret+ 1))
                               (logxor (%read64le input (+ offset 72)) s1))
                           s2 (%mul-fold64
                               (logxor (%read64le input (+ offset 80)) (aref +rapid-secret+ 2))
                               (logxor (%read64le input (+ offset 88)) s2)))
                     (incf offset 96)
                     (decf remaining 96))
            (when (>= remaining 48)
              (setf s0 (%mul-fold64
                        (logxor (%read64le input offset) (aref +rapid-secret+ 0))
                        (logxor (%read64le input (+ offset 8)) s0))
                    s1 (%mul-fold64
                        (logxor (%read64le input (+ offset 16)) (aref +rapid-secret+ 1))
                        (logxor (%read64le input (+ offset 24)) s1))
                    s2 (%mul-fold64
                        (logxor (%read64le input (+ offset 32)) (aref +rapid-secret+ 2))
                        (logxor (%read64le input (+ offset 40)) s2)))
              (incf offset 48)
              (decf remaining 48))
            (setf s0 (%u64 (logxor s0 s1 s2))))
          (when (> remaining 16)
            (setf s0 (%mul-fold64
                      (logxor (%read64le input offset) (aref +rapid-secret+ 2))
                      (logxor (%read64le input (+ offset 8)) s0 (aref +rapid-secret+ 1))))
            (when (> remaining 32)
              (setf s0 (%mul-fold64
                        (logxor (%read64le input (+ offset 16)) (aref +rapid-secret+ 2))
                        (logxor (%read64le input (+ offset 24)) s0)))))
          (setf a (%read64le input (- length 16))
                b (%read64le input (- length 8)))))
    (let* ((product (* (%u64 (logxor a (aref +rapid-secret+ 1)))
                       (%u64 (logxor b s0))))
           (low (%u64 product))
           (high (%u64 (ash product -64))))
      (%mul-fold64 (logxor low (aref +rapid-secret+ 0) length)
                   (logxor high (aref +rapid-secret+ 1))))))

(defparameter +wy-secret+
  #(#xa0761d6478bd642f #xe7037ed1a0b428db
    #x8ebc6af09c88c6e3 #x589965cc75374cc3))

(defun wyhash (bytes &optional (seed 0))
  (let* ((input (%simple-octets bytes))
         (length (length input))
         (state0 (%u64 (logxor seed
                               (%mul-fold64 (logxor seed (aref +wy-secret+ 0))
                                            (aref +wy-secret+ 1)))))
         (state1 state0) (state2 state0) (a 0) (b 0))
    (if (<= length 16)
        (cond
          ((>= length 4)
           (let ((end (- length 4))
                 (quarter (ash (ash length -3) 2)))
             (setf a (logior (ash (%read32le input 0) 32)
                             (%read32le input quarter))
                   b (logior (ash (%read32le input end) 32)
                             (%read32le input (- end quarter))))))
          ((plusp length)
           (setf a (logior (ash (aref input 0) 16)
                           (ash (aref input (ash length -1)) 8)
                           (aref input (1- length))))))
        (let ((offset 0))
          (when (>= length 48)
            (loop while (< offset (- length 48))
                  do (setf state0 (%mul-fold64
                                   (logxor (%read64le input offset) (aref +wy-secret+ 1))
                                   (logxor (%read64le input (+ offset 8)) state0))
                           state1 (%mul-fold64
                                   (logxor (%read64le input (+ offset 16)) (aref +wy-secret+ 2))
                                   (logxor (%read64le input (+ offset 24)) state1))
                           state2 (%mul-fold64
                                   (logxor (%read64le input (+ offset 32)) (aref +wy-secret+ 3))
                                   (logxor (%read64le input (+ offset 40)) state2)))
                     (incf offset 48))
            (setf state0 (%u64 (logxor state0 state1 state2))))
          (loop while (< (+ offset 16) length)
                do (setf state0 (%mul-fold64
                                 (logxor (%read64le input offset) (aref +wy-secret+ 1))
                                 (logxor (%read64le input (+ offset 8)) state0)))
                   (incf offset 16))
          (setf a (%read64le input (- length 16))
                b (%read64le input (- length 8)))))
    (let* ((product (* (%u64 (logxor a (aref +wy-secret+ 1)))
                       (%u64 (logxor b state0))))
           (low (%u64 product))
           (high (%u64 (ash product -64))))
      (%mul-fold64 (logxor low (aref +wy-secret+ 0) length)
                   (logxor high (aref +wy-secret+ 1))))))

;;; Classic xxHash ------------------------------------------------------------

(defconstant +xx-p32-1+ #x9e3779b1)
(defconstant +xx-p32-2+ #x85ebca77)
(defconstant +xx-p32-3+ #xc2b2ae3d)
(defconstant +xx-p32-4+ #x27d4eb2f)
(defconstant +xx-p32-5+ #x165667b1)
(defconstant +xx-p64-1+ #x9e3779b185ebca87)
(defconstant +xx-p64-2+ #xc2b2ae3d27d4eb4f)
(defconstant +xx-p64-3+ #x165667b19e3779f9)
(defconstant +xx-p64-4+ #x85ebca77c2b2ae63)
(defconstant +xx-p64-5+ #x27d4eb2f165667c5)

(defun %xx32-round (acc input)
  (%mul32 (%rotl32 (%u32 (+ acc (%mul32 input +xx-p32-2+))) 13) +xx-p32-1+))

(defun %xx32-avalanche (h)
  (setf h (%u32 (logxor h (ash h -15)))
        h (%mul32 h +xx-p32-2+)
        h (%u32 (logxor h (ash h -13)))
        h (%mul32 h +xx-p32-3+))
  (%u32 (logxor h (ash h -16))))

(defun xxhash32 (bytes &optional (seed 0))
  (let* ((input (%simple-octets bytes)) (length (length input)) (offset 0) h)
    (if (>= length 16)
        (let ((v1 (%u32 (+ seed +xx-p32-1+ +xx-p32-2+)))
              (v2 (%u32 (+ seed +xx-p32-2+)))
              (v3 (%u32 seed))
              (v4 (%u32 (- seed +xx-p32-1+))))
          (loop while (<= (+ offset 16) length)
                do (setf v1 (%xx32-round v1 (%read32le input offset))
                         v2 (%xx32-round v2 (%read32le input (+ offset 4)))
                         v3 (%xx32-round v3 (%read32le input (+ offset 8)))
                         v4 (%xx32-round v4 (%read32le input (+ offset 12))))
                   (incf offset 16))
          (setf h (%u32 (+ (%rotl32 v1 1) (%rotl32 v2 7)
                             (%rotl32 v3 12) (%rotl32 v4 18)))))
        (setf h (%u32 (+ seed +xx-p32-5+))))
    (setf h (%u32 (+ h length)))
    (loop while (<= (+ offset 4) length)
          do (setf h (%u32 (+ h (%mul32 (%read32le input offset) +xx-p32-3+)))
                   h (%mul32 (%rotl32 h 17) +xx-p32-4+))
             (incf offset 4))
    (loop while (< offset length)
          do (setf h (%u32 (+ h (* (aref input offset) +xx-p32-5+)))
                   h (%mul32 (%rotl32 h 11) +xx-p32-1+))
             (incf offset))
    (%xx32-avalanche h)))

(defun %xx64-round (acc input)
  (%mul64 (%rotl64 (%u64 (+ acc (%mul64 input +xx-p64-2+))) 31) +xx-p64-1+))

(defun %xx64-merge (acc value)
  (%u64 (+ (%mul64 (logxor acc (%xx64-round 0 value)) +xx-p64-1+)
           +xx-p64-4+)))

(defun %xx64-avalanche (h)
  (setf h (%u64 (logxor h (ash h -33)))
        h (%mul64 h +xx-p64-2+)
        h (%u64 (logxor h (ash h -29)))
        h (%mul64 h +xx-p64-3+))
  (%u64 (logxor h (ash h -32))))

(defun xxhash64 (bytes &optional (seed 0))
  (let* ((input (%simple-octets bytes)) (length (length input)) (offset 0) h)
    (if (>= length 32)
        (let ((v1 (%u64 (+ seed +xx-p64-1+ +xx-p64-2+)))
              (v2 (%u64 (+ seed +xx-p64-2+)))
              (v3 (%u64 seed))
              (v4 (%u64 (- seed +xx-p64-1+))))
          (loop while (<= (+ offset 32) length)
                do (setf v1 (%xx64-round v1 (%read64le input offset))
                         v2 (%xx64-round v2 (%read64le input (+ offset 8)))
                         v3 (%xx64-round v3 (%read64le input (+ offset 16)))
                         v4 (%xx64-round v4 (%read64le input (+ offset 24))))
                   (incf offset 32))
          (setf h (%u64 (+ (%rotl64 v1 1) (%rotl64 v2 7)
                             (%rotl64 v3 12) (%rotl64 v4 18)))
                h (%xx64-merge h v1)
                h (%xx64-merge h v2)
                h (%xx64-merge h v3)
                h (%xx64-merge h v4)))
        (setf h (%u64 (+ seed +xx-p64-5+))))
    (setf h (%u64 (+ h length)))
    (loop while (<= (+ offset 8) length)
          for k = (%xx64-round 0 (%read64le input offset))
          do (setf h (%u64 (logxor h k))
                   h (%u64 (+ (%mul64 (%rotl64 h 27) +xx-p64-1+) +xx-p64-4+)))
             (incf offset 8))
    (when (<= (+ offset 4) length)
      (setf h (%u64 (logxor h (%mul64 (%read32le input offset) +xx-p64-1+)))
            h (%u64 (+ (%mul64 (%rotl64 h 23) +xx-p64-2+) +xx-p64-3+)))
      (incf offset 4))
    (loop while (< offset length)
          do (setf h (%u64 (logxor h (%mul64 (aref input offset) +xx-p64-5+)))
                   h (%mul64 (%rotl64 h 11) +xx-p64-1+))
             (incf offset))
    (%xx64-avalanche h)))

;;; XXH3 ----------------------------------------------------------------------

(defconstant +xxh3-mx1+ #x165667919e3779f9)
(defconstant +xxh3-mx2+ #x9fb21c651e98df25)

(defparameter +xxh3-secret+
  (coerce
   '(#xb8 #xfe #x6c #x39 #x23 #xa4 #x4b #xbe #x7c #x01 #x81 #x2c #xf7 #x21 #xad #x1c
     #xde #xd4 #x6d #xe9 #x83 #x90 #x97 #xdb #x72 #x40 #xa4 #xa4 #xb7 #xb3 #x67 #x1f
     #xcb #x79 #xe6 #x4e #xcc #xc0 #xe5 #x78 #x82 #x5a #xd0 #x7d #xcc #xff #x72 #x21
     #xb8 #x08 #x46 #x74 #xf7 #x43 #x24 #x8e #xe0 #x35 #x90 #xe6 #x81 #x3a #x26 #x4c
     #x3c #x28 #x52 #xbb #x91 #xc3 #x00 #xcb #x88 #xd0 #x65 #x8b #x1b #x53 #x2e #xa3
     #x71 #x64 #x48 #x97 #xa2 #x0d #xf9 #x4e #x38 #x19 #xef #x46 #xa9 #xde #xac #xd8
     #xa8 #xfa #x76 #x3f #xe3 #x9c #x34 #x3f #xf9 #xdc #xbb #xc7 #xc7 #x0b #x4f #x1d
     #x8a #x51 #xe0 #x4b #xcd #xb4 #x59 #x31 #xc8 #x9f #x7e #xc9 #xd9 #x78 #x73 #x64
     #xea #xc5 #xac #x83 #x34 #xd3 #xeb #xc3 #xc5 #x81 #xa0 #xff #xfa #x13 #x63 #xeb
     #x17 #x0d #xdd #x51 #xb7 #xf0 #xda #x49 #xd3 #x16 #x55 #x26 #x29 #xd4 #x68 #x9e
     #x2b #x16 #xbe #x58 #x7d #x47 #xa1 #xfc #x8f #xf8 #xb8 #xd1 #x7a #xd0 #x31 #xce
     #x45 #xcb #x3a #x8f #x95 #x16 #x04 #x28 #xaf #xd7 #xfb #xca #xbb #x4b #x40 #x7e)
   '(simple-array (unsigned-byte 8) (*))))

(defun %xxh3-avalanche (h)
  (setf h (%u64 h)
        h (%u64 (logxor h (ash h -37)))
        h (%mul64 h +xxh3-mx1+))
  (%u64 (logxor h (ash h -32))))

(defun %xxh3-rrmxmx (h length)
  (setf h (%u64 h)
        h (%u64 (logxor h (%rotl64 h 49) (%rotl64 h 24)))
        h (%mul64 h +xxh3-mx2+)
        h (%u64 (logxor h (+ (ash h -35) length)))
        h (%mul64 h +xxh3-mx2+))
  (%u64 (logxor h (ash h -28))))

(defun %xxh3-mix16 (input input-offset secret secret-offset seed)
  (%mul-fold64
   (logxor (%read64le input input-offset)
           (%u64 (+ (%read64le secret secret-offset) seed)))
   (logxor (%read64le input (+ input-offset 8))
           (%u64 (- (%read64le secret (+ secret-offset 8)) seed)))))

(defun %xxh3-short (input secret seed)
  (let ((length (length input)))
    (cond
      ((> length 16)
       (let ((acc (%mul64 length +xx-p64-1+)))
         (cond
           ((<= length 128)
            (when (> length 32)
              (when (> length 64)
                (when (> length 96)
                  (incf acc (%xxh3-mix16 input 48 secret 96 seed))
                  (incf acc (%xxh3-mix16 input (- length 64) secret 112 seed)))
                (incf acc (%xxh3-mix16 input 32 secret 64 seed))
                (incf acc (%xxh3-mix16 input (- length 48) secret 80 seed)))
              (incf acc (%xxh3-mix16 input 16 secret 32 seed))
              (incf acc (%xxh3-mix16 input (- length 32) secret 48 seed)))
            (incf acc (%xxh3-mix16 input 0 secret 0 seed))
            (incf acc (%xxh3-mix16 input (- length 16) secret 16 seed))
            (%xxh3-avalanche acc))
           (t
            (dotimes (i 8)
              (incf acc (%xxh3-mix16 input (* 16 i) secret (* 16 i) seed)))
            (let ((acc-end (%xxh3-mix16 input (- length 16) secret 119 seed))
                  (rounds (floor length 16)))
              (setf acc (%xxh3-avalanche acc))
              (loop for i from 8 below rounds
                    do (incf acc-end
                             (%xxh3-mix16 input (* 16 i) secret (+ (* 16 (- i 8)) 3) seed)))
              (%xxh3-avalanche (+ acc acc-end)))))))
      ((> length 8)
       (let* ((bitflip1 (%u64 (+ (logxor (%read64le secret 24) (%read64le secret 32)) seed)))
              (bitflip2 (%u64 (- (logxor (%read64le secret 40) (%read64le secret 48)) seed)))
              (low (logxor (%read64le input 0) bitflip1))
              (high (logxor (%read64le input (- length 8)) bitflip2)))
         (%xxh3-avalanche (+ length (%swap64 low) high (%mul-fold64 low high)))))
      ((>= length 4)
       (let* ((s (%u64 (logxor seed (ash (%swap32 (%u32 seed)) 32))))
              (input1 (%read32le input 0))
              (input2 (%read32le input (- length 4)))
              (bitflip (%u64 (- (logxor (%read64le secret 8) (%read64le secret 16)) s)))
              (input64 (+ input2 (ash input1 32))))
         (%xxh3-rrmxmx (logxor input64 bitflip) length)))
      ((plusp length)
       (let* ((combined (logior (ash (aref input 0) 16)
                                (ash (aref input (ash length -1)) 24)
                                (aref input (1- length))
                                (ash length 8)))
              (bitflip (%u64 (+ (logxor (%read32le secret 0) (%read32le secret 4)) seed))))
         (%xx64-avalanche (logxor combined bitflip))))
      (t (%xx64-avalanche (logxor seed
                                  (logxor (%read64le secret 56) (%read64le secret 64))))))))

(defun %xxh3-accumulate (acc input input-offset secret secret-offset)
  (dotimes (i 8)
    (let* ((data (%read64le input (+ input-offset (* i 8))))
           (keyed (logxor data (%read64le secret (+ secret-offset (* i 8)))))
           (product (* (ldb (byte 32 0) keyed) (ldb (byte 32 32) keyed))))
      (setf (aref acc i)
            (%u64 (+ (aref acc i)
                     (%read64le input (+ input-offset (* (logxor i 1) 8)))
                     product))))))

(defun %xxh3-scramble (acc secret offset)
  (dotimes (i 8)
    (let ((value (aref acc i)))
      (setf value (%u64 (logxor value (ash value -47)))
            value (%u64 (logxor value (%read64le secret (+ offset (* i 8)))))
            (aref acc i) (%mul64 value +xx-p32-1+)))))

(defun %xxh3-long (input secret)
  (let* ((length (length input))
         (acc (vector +xx-p32-3+ +xx-p64-1+ +xx-p64-2+ +xx-p64-3+
                      +xx-p64-4+ +xx-p32-2+ +xx-p64-5+ +xx-p32-1+))
         (stripes-per-block 16)
         (block-length 1024)
         (blocks (floor (1- length) block-length)))
    (dotimes (block blocks)
      (dotimes (stripe stripes-per-block)
        (%xxh3-accumulate acc input (+ (* block block-length) (* stripe 64))
                          secret (* stripe 8)))
      (%xxh3-scramble acc secret 128))
    (let* ((last-block (* blocks block-length))
           (stripes (floor (- (1- length) last-block) 64)))
      (dotimes (stripe stripes)
        (%xxh3-accumulate acc input (+ last-block (* stripe 64)) secret (* stripe 8))))
    (%xxh3-accumulate acc input (- length 64) secret 121)
    (let ((result (%mul64 length +xx-p64-1+)))
      (dotimes (i 4)
        (incf result
              (%mul-fold64
               (logxor (aref acc (* i 2)) (%read64le secret (+ 11 (* i 16))))
               (logxor (aref acc (1+ (* i 2))) (%read64le secret (+ 19 (* i 16)))))))
      (%xxh3-avalanche result))))

(defun xxhash3 (bytes &optional (seed 0))
  (let* ((input (%simple-octets bytes))
         ;; Bun.hash.xxHash3 deliberately truncates its seed to u32.
         (seed (%u32 seed)))
    (if (<= (length input) 240)
        (%xxh3-short input +xxh3-secret+ seed)
        (if (zerop seed)
            (%xxh3-long input +xxh3-secret+)
            (let ((secret (make-array 192 :element-type '(unsigned-byte 8))))
              (dotimes (i 12)
                (%write64le secret (* i 16)
                            (%u64 (+ (%read64le +xxh3-secret+ (* i 16)) seed)))
                (%write64le secret (+ (* i 16) 8)
                            (%u64 (- (%read64le +xxh3-secret+ (+ (* i 16) 8)) seed))))
              (%xxh3-long input secret))))))

;;; CityHash ------------------------------------------------------------------

(defconstant +city-c1+ #xcc9e2d51)
(defconstant +city-c2+ #x1b873593)
(defconstant +city-k0+ #xc3a5c85c97cb3127)
(defconstant +city-k1+ #xb492b66fbe98f273)
(defconstant +city-k2+ #x9ae16a3b2f90404f)

(defun %city-mur (a h)
  (setf a (%mul32 a +city-c1+)
        a (%rotr32 a 17)
        a (%mul32 a +city-c2+)
        h (%u32 (logxor h a))
        h (%rotr32 h 19))
  (%u32 (+ (%mul32 h 5) #xe6546b64)))

(defun city-hash32 (bytes &optional seed)
  (declare (ignore seed))
  (let* ((s (%simple-octets bytes)) (length (length s)))
    (cond
      ((<= length 4)
       (let ((b 0) (c 9))
         (loop for value across s
               for signed = (if (> value 127) (- value 256) value)
               do (setf b (%u32 (+ (%mul32 b +city-c1+) signed))
                        c (%u32 (logxor c b))))
         (%fmix32 (%city-mur b (%city-mur length c)))))
      ((<= length 12)
       (let* ((a length) (b (%mul32 length 5)) (c 9) (d b))
         (incf a (%read32le s 0))
         (incf b (%read32le s (- length 4)))
         (incf c (%read32le s (logand (ash length -1) 4)))
         (%fmix32 (%city-mur c (%city-mur b (%city-mur a d))))))
      ((<= length 24)
       (let ((a (%read32le s (- (ash length -1) 4)))
             (b (%read32le s 4))
             (c (%read32le s (- length 8)))
             (d (%read32le s (ash length -1)))
             (e (%read32le s 0))
             (f (%read32le s (- length 4))))
         (%fmix32 (%city-mur f (%city-mur e (%city-mur d (%city-mur c (%city-mur b (%city-mur a length)))))))))
      (t
       (let* ((h (%u32 length))
              (g (%mul32 +city-c1+ length))
              (f g)
              (a0 (%mul32 (%rotr32 (%mul32 (%read32le s (- length 4)) +city-c1+) 17) +city-c2+))
              (a1 (%mul32 (%rotr32 (%mul32 (%read32le s (- length 8)) +city-c1+) 17) +city-c2+))
              (a2 (%mul32 (%rotr32 (%mul32 (%read32le s (- length 16)) +city-c1+) 17) +city-c2+))
              (a3 (%mul32 (%rotr32 (%mul32 (%read32le s (- length 12)) +city-c1+) 17) +city-c2+))
              (a4 (%mul32 (%rotr32 (%mul32 (%read32le s (- length 20)) +city-c1+) 17) +city-c2+))
              (offset 0))
         (setf h (%u32 (logxor h a0)) h (%u32 (+ (%mul32 (%rotr32 h 19) 5) #xe6546b64))
               h (%u32 (logxor h a2)) h (%u32 (+ (%mul32 (%rotr32 h 19) 5) #xe6546b64))
               g (%u32 (logxor g a1)) g (%u32 (+ (%mul32 (%rotr32 g 19) 5) #xe6546b64))
               g (%u32 (logxor g a3)) g (%u32 (+ (%mul32 (%rotr32 g 19) 5) #xe6546b64))
               f (%u32 (+ f a4)) f (%u32 (+ (%mul32 (%rotr32 f 19) 5) #xe6546b64)))
         (dotimes (iteration (floor (1- length) 20))
           (let ((b0 (%mul32 (%rotr32 (%mul32 (%read32le s offset) +city-c1+) 17) +city-c2+))
                 (b1 (%read32le s (+ offset 4)))
                 (b2 (%mul32 (%rotr32 (%mul32 (%read32le s (+ offset 8)) +city-c1+) 17) +city-c2+))
                 (b3 (%mul32 (%rotr32 (%mul32 (%read32le s (+ offset 12)) +city-c1+) 17) +city-c2+))
                 (b4 (%read32le s (+ offset 16))))
             (setf h (%u32 (logxor h b0)) h (%u32 (+ (%mul32 (%rotr32 h 18) 5) #xe6546b64))
                   f (%u32 (+ f b1)) f (%mul32 (%rotr32 f 19) +city-c1+)
                   g (%u32 (+ g b2)) g (%u32 (+ (%mul32 (%rotr32 g 18) 5) #xe6546b64))
                   h (%u32 (logxor h (%u32 (+ b3 b1))))
                   h (%u32 (+ (%mul32 (%rotr32 h 19) 5) #xe6546b64))
                   g (%u32 (logxor g b4)) g (%mul32 (%swap32 g) 5)
                   h (%swap32 (%u32 (+ h (%mul32 b4 5))))
                   f (%u32 (+ f b0)))
             (rotatef h f g)
             (incf offset 20)))
         (setf g (%mul32 (%rotr32 g 11) +city-c1+) g (%mul32 (%rotr32 g 17) +city-c1+)
               f (%mul32 (%rotr32 f 11) +city-c1+) f (%mul32 (%rotr32 f 17) +city-c1+)
               h (%rotr32 (%u32 (+ h g)) 19) h (%u32 (+ (%mul32 h 5) #xe6546b64))
               h (%mul32 (%rotr32 h 17) +city-c1+)
               h (%rotr32 (%u32 (+ h f)) 19) h (%u32 (+ (%mul32 h 5) #xe6546b64))
               h (%mul32 (%rotr32 h 17) +city-c1+))
         h)))))

(defun %city-shiftmix (v)
  (let ((word (%u64 v)))
    (%u64 (logxor word (ash word -47)))))
(defun %city-hash16-mul (low high mul)
  (let ((a (%mul64 (logxor low high) mul)))
    (setf a (%u64 (logxor a (ash a -47))))
    (let ((b (%mul64 (logxor high a) mul)))
      (setf b (%u64 (logxor b (ash b -47))))
      (%mul64 b mul))))
(defun %city-hash16 (low high) (%city-hash16-mul low high #x9ddfea08eb382d69))

(defun %city-weak32 (s offset a b)
  (let* ((w (%read64le s offset)) (x (%read64le s (+ offset 8)))
         (y (%read64le s (+ offset 16))) (z (%read64le s (+ offset 24))))
    (setf a (%u64 (+ a w))
          b (%rotr64 (%u64 (+ b a z)) 21))
    (let ((c a))
      (setf a (%u64 (+ a x y))
            b (%u64 (+ b (%rotr64 a 44))))
      (values (%u64 (+ a z)) (%u64 (+ b c))))))

(defun %city64-base (s)
  (let ((length (length s)))
    (cond
      ((<= length 16)
       (cond
         ((>= length 8)
          (let* ((mul (%u64 (+ +city-k2+ (* length 2))))
                 (a (%u64 (+ (%read64le s 0) +city-k2+)))
                 (b (%read64le s (- length 8)))
                 (c (%u64 (+ (%mul64 (%rotr64 b 37) mul) a)))
                 (d (%mul64 (%u64 (+ (%rotr64 a 25) b)) mul)))
            (%city-hash16-mul c d mul)))
         ((>= length 4)
          (let ((mul (%u64 (+ +city-k2+ (* length 2))))
                (a (%read32le s 0)))
            (%city-hash16-mul (+ length (ash a 3)) (%read32le s (- length 4)) mul)))
         ((plusp length)
          (let* ((a (aref s 0)) (b (aref s (ash length -1))) (c (aref s (1- length)))
                 (y (%u32 (+ a (ash b 8)))) (z (%u32 (+ length (ash c 2)))))
            (%mul64 (%city-shiftmix (logxor (%mul64 y +city-k2+) (%mul64 z +city-k0+))) +city-k2+)))
         (t +city-k2+)))
      ((<= length 32)
       (let* ((mul (%u64 (+ +city-k2+ (* length 2))))
              (a (%mul64 (%read64le s 0) +city-k1+))
              (b (%read64le s 8))
              (c (%mul64 (%read64le s (- length 8)) mul))
              (d (%mul64 (%read64le s (- length 16)) +city-k2+)))
         (%city-hash16-mul
          (%u64 (+ (%rotr64 (+ a b) 43) (%rotr64 c 30) d))
          (%u64 (+ a (%rotr64 (+ b +city-k2+) 18) c)) mul)))
      ((<= length 64)
       (let* ((mul (%u64 (+ +city-k2+ (* length 2))))
              (a (%mul64 (%read64le s 0) +city-k2+)) (b (%read64le s 8))
              (c (%read64le s (- length 24))) (d (%read64le s (- length 32)))
              (e (%mul64 (%read64le s 16) +city-k2+)) (f (%mul64 (%read64le s 24) 9))
              (g (%read64le s (- length 8))) (h (%mul64 (%read64le s (- length 16)) mul))
              (u (%u64 (+ (%rotr64 (+ a g) 43) (%mul64 (+ (%rotr64 b 30) c) 9))))
              (v (%u64 (+ (logxor (+ a g) d) f 1)))
              (w (%u64 (+ (%swap64 (%mul64 (+ u v) mul)) h)))
              (x (%u64 (+ (%rotr64 (+ e f) 42) c)))
              (y (%mul64 (%u64 (+ (%swap64 (%mul64 (+ v w) mul)) g)) mul))
              (z (%u64 (+ e f c)))
              (a1 (%u64 (+ (%swap64 (%u64 (+ (%mul64 (+ x z) mul) y))) b)))
              (b1 (%mul64 (%city-shiftmix (+ (%mul64 (+ z a1) mul) d h)) mul)))
         (%u64 (+ b1 x))))
      (t
       (let* ((remaining (%u64 length))
              (x (%read64le s (- length 40)))
              (y (%u64 (+ (%read64le s (- length 16)) (%read64le s (- length 56)))))
              (z (%city-hash16 (+ (%read64le s (- length 48)) remaining)
                               (%read64le s (- length 24))))
              v1 v2 w1 w2 (offset 0))
         (multiple-value-setq (v1 v2) (%city-weak32 s (- length 64) remaining z))
         (multiple-value-setq (w1 w2) (%city-weak32 s (- length 32) (+ y +city-k1+) x))
         (setf x (%u64 (+ (%mul64 x +city-k1+) (%read64le s 0)))
               remaining (logand (1- remaining) (lognot 63)))
         (loop
           (setf x (%mul64 (%rotr64 (+ x y v1 (%read64le s (+ offset 8))) 37) +city-k1+)
                 y (%mul64 (%rotr64 (+ y v2 (%read64le s (+ offset 48))) 42) +city-k1+)
                 x (%u64 (logxor x w2))
                 y (%u64 (+ y v1 (%read64le s (+ offset 40))))
                 z (%mul64 (%rotr64 (+ z w1) 33) +city-k1+))
           (multiple-value-setq (v1 v2)
             (%city-weak32 s offset (%mul64 v2 +city-k1+) (+ x w1)))
           (multiple-value-setq (w1 w2)
             (%city-weak32 s (+ offset 32) (+ z w2) (+ y (%read64le s (+ offset 16)))))
           (rotatef z x)
           (incf offset 64)
           (decf remaining 64)
           (when (zerop remaining) (return)))
         (%city-hash16
          (+ (%city-hash16 v1 w1) (%mul64 (%city-shiftmix y) +city-k1+) z)
          (+ (%city-hash16 v2 w2) x)))))))

(defun city-hash64 (bytes &optional (seed 0))
  (%city-hash16 (%u64 (- (%city64-base (%simple-octets bytes)) +city-k2+)) seed))

(defun hash-octets (algorithm bytes &optional (seed 0))
  (ecase algorithm
    ((:wyhash :default) (wyhash bytes seed))
    (:adler32 (adler32 bytes seed))
    (:crc32 (crc32 bytes seed))
    (:city-hash32 (city-hash32 bytes seed))
    (:city-hash64 (city-hash64 bytes seed))
    (:xxhash32 (xxhash32 bytes seed))
    (:xxhash64 (xxhash64 bytes seed))
    (:xxhash3 (xxhash3 bytes seed))
    (:murmur32v2 (murmur32v2 bytes seed))
    (:murmur32v3 (murmur32v3 bytes seed))
    (:murmur64v2 (murmur64v2 bytes seed))
    (:rapidhash (rapidhash bytes seed))))
