;;;; yaml-tests.lisp -- engine-free Phase 31 parser contract.

(in-package :clun-test)

(defun yaml-document (source &optional (index 0))
  (aref (yaml:yaml-stream-documents (yaml:parse-yaml source)) index))

(defun yaml-map-node (mapping key)
  (loop for pair across (yaml:yaml-node-value mapping)
        for key-node = (yaml:yaml-pair-key pair)
        when (and (eq (yaml:yaml-node-kind key-node) :string)
                  (string= (yaml:yaml-node-value key-node) key))
          return (yaml:yaml-pair-value pair)))

(define-test yaml/core-scalars
  (dolist (row (list (list "" :null nil)
                     (list "~" :null nil)
                     (list "null" :null nil)
                     (list "TRUE" :boolean t)
                     (list "false" :boolean nil)
                     (list "42" :number 42)
                     (list "-0x10" :number -16)
                     (list "0o17" :number 15)
                     (list "1.25e2" :number 125d0)
                     (list ".5" :number 0.5d0)
                     (list "1." :number 1d0)
                     (list ".inf" :number :positive-infinity)
                     (list "-.INF" :number :negative-infinity)
                     (list ".NaN" :number :nan)
                     (list "yes" :string "yes")
                     (list "1_000" :string "1_000")
                     (list "+.nan" :string "+.nan")
                     (list "-.nan" :string "-.nan")))
    (let ((node (yaml-document (first row))))
      (is eq (second row) (yaml:yaml-node-kind node) "scalar ~s" (first row))
      (if (and (numberp (third row)) (floatp (third row)))
          (is = (third row) (yaml:yaml-node-value node) "scalar ~s" (first row))
          (is equal (third row) (yaml:yaml-node-value node) "scalar ~s" (first row)))))
  (let ((negative-zero (yaml:yaml-node-value (yaml-document "-0"))))
    (true (and (floatp negative-zero) (minusp (float-sign negative-zero)))))
  (is eq :positive-infinity (yaml:yaml-node-value (yaml-document "1e99999")))
  (is eq :positive-infinity
      (yaml:yaml-node-value (yaml-document (make-string 2048 :initial-element #\9))))
  (let ((underflow (yaml:yaml-node-value (yaml-document "-1e-99999"))))
    (true (and (floatp underflow) (minusp (float-sign underflow))))))

(define-test yaml/block-flow-and-tags
  (let* ((root (yaml-document
                (format nil "name: clun~%items: [1, true, null, {nested: value}]~%quoted: '42'~%")))
         (items (yaml-map-node root "items")))
    (is eq :mapping (yaml:yaml-node-kind root))
    (is equal "clun" (yaml:yaml-node-value (yaml-map-node root "name")))
    (is = 4 (length (yaml:yaml-node-value items)))
    (is eq :mapping (yaml:yaml-node-kind (aref (yaml:yaml-node-value items) 3)))
    (is equal "42" (yaml:yaml-node-value (yaml-map-node root "quoted"))))
  (let ((root (yaml-document (format nil "~ca: 1~%" (code-char #xfeff)))))
    (is = 1 (yaml:yaml-node-value (yaml-map-node root "a"))))
  (let* ((sequence (yaml-document
                    (format nil "- name: first~%  value: 1~%- name: second~%  value: 2~%")))
         (second (aref (yaml:yaml-node-value sequence) 1)))
    (is = 2 (length (yaml:yaml-node-value sequence)))
    (is equal "second" (yaml:yaml-node-value (yaml-map-node second "name")))
    (is = 2 (yaml:yaml-node-value (yaml-map-node second "value"))))
  (let ((tagged (yaml-document "!!str 42")))
    (is eq :string (yaml:yaml-node-kind tagged))
    (is equal "42" (yaml:yaml-node-value tagged)))
  (let ((tagged (yaml-document "!!int nope")))
    (is eq :string (yaml:yaml-node-kind tagged))
    (is equal "nope" (yaml:yaml-node-value tagged)))
  (let ((tagged (yaml-document "!!int \"42\"")))
    (is eq :string (yaml:yaml-node-kind tagged))
    (is equal "42" (yaml:yaml-node-value tagged)))
  (let ((tagged (yaml-document "!private value")))
    (is eq :string (yaml:yaml-node-kind tagged))
    (is equal "value" (yaml:yaml-node-value tagged)))
  (let ((tagged (yaml-document "! 12")))
    (is eq :string (yaml:yaml-node-kind tagged))
    (is equal "12" (yaml:yaml-node-value tagged)))
  (let ((tagged (yaml-document
                 (format nil "%TAG !! tag:example.com,2000:app/~%---~%!!int 1 - 3~%"))))
    (is eq :string (yaml:yaml-node-kind tagged))
    (is equal "1 - 3" (yaml:yaml-node-value tagged)))
  (let ((astral (yaml:yaml-node-value (yaml-document "\"\\uD83D\\uDE00\""))))
    (is = 2 (length astral))
    (is = #xd83d (char-code (char astral 0)))
    (is = #xde00 (char-code (char astral 1))))
  (let ((root (yaml-document (format nil "? explicit~%: value~%? omitted~%"))))
    (is equal "value" (yaml:yaml-node-value (yaml-map-node root "explicit")))
    (is eq :null (yaml:yaml-node-kind (yaml-map-node root "omitted"))))
  (let* ((sequence (yaml-document (format nil "- ? key~%  : value~%")))
         (mapping (aref (yaml:yaml-node-value sequence) 0)))
    (is equal "value" (yaml:yaml-node-value (yaml-map-node mapping "key"))))
  (let* ((root (yaml-document
                (format nil
                        "packages:~%  ? /@types/node@20.0.0~%  : dependencies:~%      undici-types: 5.0.0~%    dev: true~%")))
         (package (yaml-map-node (yaml-map-node root "packages") "/@types/node@20.0.0"))
         (dependencies (yaml-map-node package "dependencies")))
    (is equal "5.0.0" (yaml:yaml-node-value (yaml-map-node dependencies "undici-types")))
    (is eq :boolean (yaml:yaml-node-kind (yaml-map-node package "dev")))))

(define-test yaml/anchors-merges-and-duplicates
  (let* ((root (yaml-document
                (format nil
                        "defaults: &base {a: 1, b: 2}~%first: *base~%merged:~%  <<: *base~%  b: 3~%dup: old~%dup: new~%")))
         (defaults (yaml-map-node root "defaults"))
         (first (yaml-map-node root "first"))
         (merged (yaml-map-node root "merged")))
    (true (eq defaults first))
    (true (eq (yaml-map-node defaults "a") (yaml-map-node merged "a")))
    (is = 3 (yaml:yaml-node-value (yaml-map-node merged "b")))
    (is equal "new" (yaml:yaml-node-value (yaml-map-node root "dup")))
    (is = 4 (length (yaml:yaml-node-value root))))
  (let ((root (yaml-document (format nil "&root~%self: *root~%"))))
    (true (eq root (yaml-map-node root "self"))))
  (let* ((root (yaml-document (format nil "? &key [*key]~%: value~%")))
         (pair (aref (yaml:yaml-node-value root) 0))
         (key (yaml:yaml-pair-key pair)))
    (is eq :sequence (yaml:yaml-node-kind key))
    (true (eq key (aref (yaml:yaml-node-value key) 0)))
    (is equal "value" (yaml:yaml-node-value (yaml:yaml-pair-value pair)))))

(define-test yaml/quoted-block-and-documents
  (let* ((root (yaml-document
                (format nil
                        "double: \"line\\nvalue\"~%single: 'it''s'~%literal: |~%  one~%  two~%folded: >-~%  three~%  four~%"))))
    (is equal (format nil "line~%value")
        (yaml:yaml-node-value (yaml-map-node root "double")))
    (is equal "it's" (yaml:yaml-node-value (yaml-map-node root "single")))
    (is equal (format nil "one~%two~%")
        (yaml:yaml-node-value (yaml-map-node root "literal")))
    (is equal "three four" (yaml:yaml-node-value (yaml-map-node root "folded"))))
  (let ((root (yaml-document
               (format nil "keep: |+~%  text~%~%~%fold: >~%  a~%~%  b~%"))))
    (is equal (format nil "text~%~%~%")
        (yaml:yaml-node-value (yaml-map-node root "keep")))
    (is equal (format nil "a~%b~%")
        (yaml:yaml-node-value (yaml-map-node root "fold"))))
  (let* ((stream (yaml:parse-yaml
                  (format nil "%YAML 1.2~%---~%a: 1~%...~%---~%b: 2~%")))
         (documents (yaml:yaml-stream-documents stream)))
    (is = 2 (length documents))
    (is = 1 (yaml:yaml-node-value (yaml-map-node (aref documents 0) "a")))
    (is = 2 (yaml:yaml-node-value (yaml-map-node (aref documents 1) "b")))))

(define-test yaml/rejects-invalid-and-unsafe-input
  (fail (yaml:parse-yaml "*missing") yaml:yaml-error)
  (fail (yaml:parse-yaml (format nil "a:~%~cb: 1~%" #\Tab)) yaml:yaml-error)
  (fail (yaml:parse-yaml (format nil "a: ~c~%" (code-char 1))) yaml:yaml-error)
  (fail (yaml:parse-yaml "[1, 2") yaml:yaml-error)
  (fail (yaml:parse-yaml "\"\\uD83D\"") yaml:yaml-error)
  (fail (yaml:parse-yaml "\"\\uDE00\"") yaml:yaml-error)
  (let ((root (yaml-document (format nil "%YAML 1.1~%---~%a: 1~%"))))
    (is = 1 (yaml:yaml-node-value (yaml-map-node root "a"))))
  (fail (yaml:parse-yaml
         (concatenate 'string (make-string 258 :initial-element #\[)
                      "0" (make-string 258 :initial-element #\])))
        yaml:yaml-error)
  (fail (yaml:parse-yaml
         (with-output-to-string (output)
           (dotimes (index 1025)
             (declare (ignore index))
             (format output "---~%null~%"))))
        yaml:yaml-error))
